### ISSUE TITLE
Enhancements when finops is disabled

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1007]
**Version:** main	
**UI:** dev-da9c50b
**Commit ID:** 9151daaf6ef09f063de4f49064b8f9ee70ab5d83
**Env:** AWS EC2 Ubuntu 22.04 amd64

Currently with finops disabled, opencost still collects cost data and seal will also labels the resources in the cluster, which may consume unnecessary CPU resources.

**Comment by gitlawr** [comment]
No more valid in the latest version
