### ISSUE TITLE
The initialize form looks odd in small screen

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1169]
**Steps to reproduce**
Access a fresh Walrus setup using a small screen or minimize the browser window.

**Result**
<img width="809" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/ed69a38a-42f4-4cd9-9a56-c95ed941100d">

**Environment**
- Walrus version: main or v0.3.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 2314b9d4571c3b6b341dee7ed630a5ffc5793dfe
- UI version: dev-0835269

**Test Result:**

- Check the small screen.
<img width="1431" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b1a149d5-8b3f-4b66-b4ad-9518a60a110f">

- But unable to view full settings box when resizing the browser window as follows:
<img width="773" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3e7a49bb-9a8f-4f4a-925e-0201d34e7f82">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-6ab9dbf

**Test Result:** pass

<img width="777" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/cee806d8-1e56-498c-8351-d7cb69b28ece">
