### ISSUE TITLE
[v0.3.0][CLI]Optimizing input when using the CLI to update settings

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1172]
**Is your enhancement related to a problem? Please describe.**
When using the CLI to update settings, now we should input `<setting>` and `--name <setting>`, for example:
```
walrus setting update OpenAiApiToken --name OpenAiApiToken --value ${OPENAI_TOKEN}
```
It doesn't make sense, I think we should remove one.

**Describe the solution you'd like**
Keep `<setting>` or `--name <setting>` only.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 2314b9d4571c3b6b341dee7ed630a5ffc5793dfe
- UI version: dev-0835269

**Test Result:** pass

`--name <setting>`  has been removed.

```
 ~/.walrus/ wa setting update -h
Usage:
  walrus setting update <setting> [flags]

Flags:
      --value string
```

```
 ~/.walrus/ wa  setting update OpenAiApiToken --value "xxx"

```
