### ISSUE TITLE
Dynamic options

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1178]
**Is your enhancement related to a problem? Please describe.**
Now options in templates are hard-coded(https://seal-io.github.io/docs/operation/template#variable-style-extension)
In some cases we are not able to predefine variable options. e.g.,
- Select a namespace from existing ones.
- Select a repository from existing ones.

**Describe the solution you'd like**
Provide a way to get the options dynamically.

**Comment by Finenyaco** [comment]
Verified in a3e5c0343d3e831ca30e4fd76a160212bc5bba7f.
- Kubernetes widgets: NamespaceSelect, SecretSelect, ConfigMapSelect, StorageClassSelect
- Git widgets: GitRepoWidget, GitBranchWidget  https://github.com/seal-io/walrus/issues/1360
