### ISSUE TITLE
refactor: backgroud jobs

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1180]
**Is your enhancement related to a problem? Please describe.**

1. The registration of background jobs is odd. https://github.com/seal-io/walrus/blob/34837e37921bbcf7fdd76c92765ff5aa9eee9543/pkg/server/init_background_jobs.go#L21-L43
2. We should remove the progressing mutex.
3. We already have a Cost status syncing loop per 1 hour, but the Connector status syncer also syncs FinOps status per 5 mins.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b0c3bd4666d7e891f3713760d3223998d4388a0f
- UI version: dev-c12f198

**Test Result:** pass, it won't synchronize cost data when executing ConnectorStatusSync task now.
