### ISSUE TITLE
Support folding template configuration

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1184]
**Is your enhancement related to a problem? Please describe.**
Template configuration may include plenty of variables and make it hard to view in the UI.

**Describe the solution you'd like**
Support folding the template configuration, and fold it by default.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-3b160ec

**Test Result:** pass

<img width="2491" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0a30fe64-cd02-488f-b8ba-fc30765d2380">

<img width="2470" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a7874537-b0c1-4942-8f97-acf3119ec193">
