### ISSUE TITLE
Incorrect placeholder

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1188]
**Describe the bug**
<img width="462" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/688c55e9-e597-46ed-8454-9e801031d886">

**Environment**
- Walrus version: v0.3.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-b537b5d

**Test Result:** Failed

It should be `a service`

<img width="708" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/507edda3-30d3-4b4c-ac24-25e63450d8ec">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 7c753a44166934745fe27656a6df6744edfa3473
- UI version: dev-d735146

**Test Result:** pass
<img width="797" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/35da5c2b-61b7-4927-986e-57a7647ca121">
