### ISSUE TITLE
refactor: speed up the response of the service resources listing

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1189]
**Is your enhancement related to a problem? Please describe.**

The response of the service resources listing is slow with `withKeys` query parameter. 

Assuming the cluster is around, a service that owns 10 resources can cost almost 8s.

**Describe the solution you'd like**

Speed up the response.

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b0c3bd4666d7e891f3713760d3223998d4388a0f
- UI version: dev-c12f198

**Test Result:** pass

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e85cda92-a64a-439a-8242-848b7f2aebe3">

If the cluster is disconnected, it takes about 5s to get the resources.
<img width="2554" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8911867c-fa24-4c95-9593-8f69ab8ad867">
