### ISSUE TITLE
Update the cron expression in system settings not working as expected

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1190]
**Describe the bug**
1. In the `system settings`  tab `Task Settings` edit the  'Check service resource status' or 'Check service dependency status'
2. Edit any one, but the other  is Updated.

**Steps to reproduce**
1. Go to 'system settings' page. click tab `Task Settings`, click Basic Task edit icon.
2. Edit  'Check service resource status' 
3. Click save icon

**Result**
1. `Check service resource status` not updated, but `Check service dependency status` updated.

**Expected behavior**
`Check service resource status` updated

**Environment**
- Walrus version: main or v0.3.0

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5cf1d9ef1dcb6bd27a686a24454d760fdc19ec22
- UI version: dev-2c89dfb

**Test Result:** pass
