### ISSUE TITLE
The Clear button does not clear the catalog selection

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1191]
**Describe the bug**
The Clear button does not clear the catalog selection:
<img width="1083" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/6e18a37a-737b-4f97-bfc6-fab7090fcc02">

**Steps to reproduce**
1. Go to "Operation Hub-Templates";
2. Select a catalog;
3. Click the "Clear" button to clear the selection.

**Result**
The Clear button does not clear the catalog selection.

**Expected behavior**
The Clear button can clear the catalog selection.

**Environment**
- Walrus version: 0.3.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e06cf82a4ebf2b6ec92875dd437d8b925b3373de
- UI version: dev-b537b5d

**Test Result:** Failed

1. Enter keywords in the search box and click `Clear`. It will query the keywords first.
<img width="1492" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/79df612e-0c40-4670-ac20-8bde5030b3c0">

2. Click `Clear` again.
<img width="1556" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4e1733bd-49f9-4fb3-b4cd-6ec4ddc67a25">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-6ab9dbf

**Test Result:** pass
