### ISSUE TITLE
Icon for standalone template does not show

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1192]
**Describe the bug**
When a template is imported from a catalog, the icon is shown. 
When it's added as a standalone template, the icon is missing.

**Environment**
- Walrus version: v0.3.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-3b160ec

**Test Result:** pass

<img width="624" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/30d23dd0-982a-48cd-9e81-100f112f384b">
