### ISSUE TITLE
Support non-catalog template option to the catalog filter of Templates tab

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1193]
**Is your enhancement related to a problem? Please describe.**
When catalog templates and non-catalog templates are mixed together, it's difficult to find the non-catalog templates.

**Describe the solution you'd like**
Support for adding non-catalog template options to the catalog filter.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 068e70303c857a262eb48aa2f7f59bec0073015b
- UI version: dev-3542d28

**Test Result:** pass

<img width="1851" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3388b145-707a-4a2a-b5a4-4fbc1db8de7f">
