### ISSUE TITLE
Support adding local cluster to make k8s deployment work out of the box

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1203]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**
Add a flag to support adding local k3s to the default project, which makes it easier to try out.

**Comment by thxCode** [comment]
After a discussion with the internal team, we are not going to support this at present. The point of view is as follows,

1. Walrus is a platform to shorten the path of application deployment, the Kubernetes cluster is not the only target that Walrus focuses on. Walrus leverages a deployer, at present, a Terraform CLI, to finish the application deployment. Running a deployment is typically an elastic, asynchronous, and inherently stateless process, so a Kubernetes cluster matches this perfectly. In short, how to finish a deployment is what Walrus cares about, but where to deploy is what users care about.
2. Walrus provides an embedding Kubernetes cluster, it's like when you buy a cell phone you always have a battery. If users really want to deploy something to the embedding Kubernetes cluster, or the Kubernetes cluster specified by `--kube-config`, please try [add a Kubernetes Connector](https://seal-io.github.io/docs/concepts#connectors).
3. For a quick start, there are many ways to have a Kubernetes cluster now, [Kind](https://kind.sigs.k8s.io/docs/user/quick-start/), [K3d](https://k3d.io/), [Docker Desktop](https://docs.docker.com/desktop/kubernetes/), [Rancher Desktop](https://rancherdesktop.io/) and cloud Kuberentes services. The only concern for the user is to ensure that the target cluster is reachable from the Walrus's "battery" cluster.

**Comment by orangedeng** [comment]
Thanks for taking this seriously. My point is that the user will get distracted very easily when deploying a new k8s. The public cloud is not the first choice in many case(mostly because of the cost). And like you said, people can deploy their own cluster by them selves, but also they will lost focus when finding out how to do it.

In quick start docs, you can add k8s cluster install link to guide user to do so.
Or as the suggestion above, you already have the embed k3s cluster, why not expose it to let people get to the core of Walrus?

**Comment by rainfd** [comment]
The current version is not yet roubust enough to allow users to arbitrarily modify walrus internal k8s resources. And it is not certain that future versions will still use k8s as the basis for our orchestration. @orangedeng

**Comment by orangedeng** [comment]
Yeah, i get that. I also don't think the embed k3s is a good idea to run terraform job. So adding the k3s/k3s quick start link to the docs should be enough.

**Comment by gitlawr** [comment]
We've revisited the issue and plan to support it in the next release.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c7df6180422f672786d170721dc2afd0d8ad30f6
- UI version: dev-04f141b

**Test Result:**

Docker:
- Embedded Kubernetes cluster: pass
- Using an external Kubernetes cluster (--kubeconfig): pass

<img width="2546" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/359f6f96-4e2c-4640-9f27-a3220270773b">
