### ISSUE TITLE
Templates that have already been used cannot select other versions when creating services

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1206]
**Describe the bug**
Templates that have already been used cannot select other versions when creating services

**Steps to reproduce**
1. Use terraform-aws-vpc template create a service, select version 5.1.1
2. save
3. Create  a new service again with terraform-aws-vpc template. 

**Result**
Versions selection only 5.1.1 one option.

**Expected behavior**
Selection has all versions.

**Environment**
- Walrus version: main, 0.3.0

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-b537b5d

**Test Result:** pass

<img width="2438" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/048d0df3-85a4-4e32-a739-b2d343eb2d23">
<img width="594" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/942a6223-ae29-4905-b723-7baa58691c6e">
