### ISSUE TITLE
Service revision logs modal add fullscreen switch.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1214]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**
Service revision logs modal add fullscreen switch.

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b51994e3fdba0aaeaba9439f6c609c105e5cbb92
- UI version: dev-b537b5d

**Test Result:** pass

<img width="903" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f6e48cab-848c-4528-bafd-09a9fb1165ae">
<img width="2558" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/48049d3f-33a3-4ee6-bd47-a41800478ef0">
