### ISSUE TITLE
Remove all legacy status of entity

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1225]
1. replace all `mixin.LegacyStatus()` to `mixin.Status`
2. check status change of the entity, update status with definede status type.
3. Adjust UI
4. clean unused code of legacy status.

currently, service revision used legacy status.

**Comment by rainfd** [comment]
The original `status` of service revision is moved to `status->summaryStatus`, and the `statusMessage` is renamed to `record`.
Update the `History Revisions` and `log detail` in the service detail page please. @hibig

**Comment by rainfd** [comment]
Can't get service revision summary status from the interface v1/projects/477380128381337604/environments/477380544053641220/services/477383247014133764/revisions?watch=true

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.3.1-rc1

**Test Result:** pass

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ed21adcc5770196dc4a5654502d4a98a0987a631
- UI version: dev-1270234

**Test Result:** pass
<img width="2440" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/85c705ce-3a39-41e5-b09f-1c9660ff4627">
