### ISSUE TITLE
The terminal could not be entered when the container only supports sh

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1238]
**Describe the bug**
The terminal could not be entered when the container only supports sh.

**Environment**
- Walrus version: v0.3.0

**Additional context**
Error log:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
command terminated with exit code 126
```
Image:
`redis:alpine`

**Comment by hibig** [comment]
UI will try to connect in order of ['bash', 'sh', 'powershell', 'pwsh', 'cmd'], until the connection is successful.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5cf1d9ef1dcb6bd27a686a24454d760fdc19ec22
- UI version: dev-2c89dfb

**Test Result:** Verified `sh`

<img width="2530" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f59b06b5-6274-402c-b6f5-b7337e108a20">
