### ISSUE TITLE
Invalid value for variable when there are special characters such as "@"

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1242]
**Describe the bug**
Invalid value for variable when there are special characters such as "@"

**Steps to reproduce**
1. Go to 'App Management' > 'Project' > 'Environment' > 'Variables', create a sensitive variable with a value that includes the '@' character, such as: 'seal@123';
2. Create a service and make use of the previously defined variable.

**Result**
Error log:
```
Error: Invalid value for variable

  on main.tf line 35, in module "aws-rds":
  35:   password      = var._walrus_var_db-password

Invalid password

This was checked by the validation rule at
.terraform/modules/aws-rds/variables.tf:38,3-13.
```

**Environment**
- Walrus version: v0.3.0

**Comment by thxCode** [comment]
it's by design. the limitation comes from AWS RDS service. https://github.com/awsdocs/aws-cloudformation-user-guide/blob/c03a45977c5a506e09a22dbe05ff980bec79b805/doc_source/aws-properties-rds-database-instance.md#cfn-rds-dbinstance-masteruserpassword.
