### ISSUE TITLE
Services list can view the latest deployment logs.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1248]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

In the service list add a button can view the latest deployment logs.

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5cf1d9ef1dcb6bd27a686a24454d760fdc19ec22
- UI version: dev-2c89dfb

**Test Result:** pass

<img width="2497" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ade4cba8-e190-4e5e-a309-18c38b84d540">
