### ISSUE TITLE
Fail to show service revision log detail.

### ISSUE THREAD

**Issue by rainfd** [seal-io/walrus#1250]
**Describe the bug**
Log deatil show Request Error.

**Steps to reproduce**
1. Create a webservice service
2. Client on the log detail button.

**Result**
<img width="1512" alt="截屏2023-09-04 09 59 22" src="https://github.com/seal-io/walrus/assets/10191719/c0439a47-f447-4854-87aa-10250846f7a6">

**Expected behavior**
Show the log.

**Environment**
- UI version: dev-10d3b50

**Additional context**
The reqeust url with `//services`
`https://localhost/v1/projects/476913747965784604/environments/476913846934581788//services/476914358589338140/revisions/476914358656447004`

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5cf1d9ef1dcb6bd27a686a24454d760fdc19ec22
- UI version: dev-2c89dfb

**Test Result:** pass

<img width="876" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/27e54281-3370-4334-9b79-8557869f9f4f">
