### ISSUE TITLE
Remove remarkTags in service API

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1255]
It's nowhere in use.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.3.1-rc1

**Test Result:** pass

<img width="1419" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3f247c66-8710-4b0f-8fdc-c4ce4844eacb">

<img width="1406" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/82115af7-7f8c-46a8-b155-a6a769269e7f">
