### ISSUE TITLE
User permission table style optimization.(suggestions from the community)

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1266]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

Suggestions from the community:
1. Do not counted the number of permissions.
2. Distinguish the status of resource permission, with color red、 green and  yellow.

**Describe alternatives you've considered**

<img width="1829" alt="截屏2023-09-11 14 17 01" src="https://github.com/seal-io/walrus/assets/24664190/819c985a-bbf1-41ab-b13a-f8be6e17a24a">

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ed21adcc5770196dc4a5654502d4a98a0987a631
- UI version: dev-e2db642

**Test Result:** pass


<img width="2492" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4004e38c-1e1b-40c2-b957-5dbbcdc5d9ab">
