### ISSUE TITLE
Cannot sync the cost for helm release resources

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1274]
**Steps to reproduce**
1. Add a Kubernetes connector and enable FinOps.
2. Using `rds` template to create a service.
3. Waiting for the cost synchronization task to be executed.
4. Go to `Project` cost analysis page and check the services cost

<img width="2484" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9365b8a7-25b9-43b4-94c6-fd3df14bbe98">

**Result**

1. It did not sync the cost of `mysql` service.
<img width="2461" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/345b1ba7-7c02-4c06-bb8f-ac9f04f0b45a">

2. Check the labels of the resource on the cluster.
```
root@tx-control-plane:/# kubectl get pod/mysql-primary-0 -n default-tx27 -o jsonpath={.metadata.labels}
{"app.kubernetes.io/component":"primary","app.kubernetes.io/instance":"mysql","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mysql","controller-revision-hash":"mysql-primary-55f8966bb9","helm.sh/chart":"mysql-9.12.2","statefulset.kubernetes.io/pod-name":"mysql-primary-0"}r

root@tx-control-plane:/# kubectl get pod/mysql-standalone-0 -n default-tx27 -o jsonpath={.metadata.labels}
{"app.kubernetes.io/component":"primary","app.kubernetes.io/instance":"mysql-standalone","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mysql","controller-revision-hash":"mysql-standalone-86c764b7f6","helm.sh/chart":"mysql-9.12.2","statefulset.kubernetes.io/pod-name":"mysql-standalone-0"}
```

**Expected behavior**

Display the cost of mysql service.

**Environment**
- Walrus version: main ed21adcc5770196dc4a5654502d4a98a0987a631

**Additional context**

**Comment by gitlawr** [comment]
No more valid in the latest version
