### ISSUE TITLE
Get template version schema by versionId

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1291]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

1. Now get the schema of all template versions in one request.
2. There may actually be hundreds of versions of a template，resulting in too much data for an request.

**Describe alternatives you've considered**

1. Get one version schema, in one request.

**Additional context**

**Comment by aiwantaozi** [comment]
Added support to get version schema by versionID
