### ISSUE TITLE
Failed to initialize the catalog when the certificate of catalog server is not valid 

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1296]
**Describe the bug**
Failed to initialize the catalog when the certificate of catalog server is not valid.

**Steps to reproduce**
1. Go to 'Operation Hub -> Catalogs', add a catalog, using Gitlab type.

**Result**
Failed to initialize the catalog, as shown below:
<img width="1448" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/db0b06bd-d9a5-47e8-a37e-5e7c3624985f">

**Environment**
- Walrus version: v0.3.1

**Comment by Finenyaco** [comment]
The gitlab server with self-signed certificates is not currently supported.
<img width="2483" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fae3cad4-5f21-4c63-9fc5-0e1b700b3967">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 700176d7801e24b89a6f2f308db96436be6be8e5
- UI version: dev-43c5e24

**Test Result:** pass

After enabling `Skip certificate authentication` in system settings, it can initialize the catalog with a self-signed certificate.
<img width="557" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/57dbb0ed-f8da-4957-816f-7ee868becdaf">
