### ISSUE TITLE
Failed to reset tag when sync template

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1297]
**Describe the bug**
An error was reported while refreshing the catalog:
```
Failed to reset to tag <some_tag>: object not found
```

**Steps to reproduce**
1. Go to 'Operation Hub -> Catalogs', add a catalog by using `https://github.com/terraform-aws-modules`;
2. Watching the log of walrus container.

**Result**
There are some errors occur:
<img width="522" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/8b8ac929-2833-47da-892d-744e3723ddf7">

**Environment**
- Walrus version: v0.3.1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 96c9574ea9fee1bad195827be7db27d629f416a6
- UI version: dev-5976040

**Test Result:** pass
