### ISSUE TITLE
Failed to initialize catalog by using Gitlab 9.0.5 as the catalog server

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1298]
**Describe the bug**
Failed to initialize catalog by using Gitlab 9.0.5 as the catalog server.

**Steps to reproduce**
Go to 'Operation Hub -> Catalog', add a catalog and using Gitlab type, some key info as show below:
- Gitlab version: 9.0.5
- Gitlab protocol: http
- Gitlab port: 8090

**Result**
An error was reported:
`401 Unauthorized`
<img width="526" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/c8ca33d9-eea8-4224-b4ee-3ce5436e80cc">
<img width="1048" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/7aa2d020-cd90-4a24-8134-f04b65d76698">
<img width="716" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/37987c2d-d129-4862-8e93-56dbf21f382c">
![image](https://github.com/seal-io/walrus/assets/42955482/3beb1909-6aca-4a7e-a710-74cfb9fca123)

**Environment**
- Walrus version: v0.3.1

**Comment by Finenyaco** [comment]
The GitLab API v3 was removed in [GitLab 11.0](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36819). Some old API requests are incompatible.

<img width="696" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7afb1271-2c59-4801-819b-a18fd3f42811">

<img width="1162" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/04354860-64c4-403c-96ac-087456b1dc8d">
