### ISSUE TITLE
Support service draft and resource recycle

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1316]
At present, we are facing the following problems:
- Currently, when deploying a service, we need to configure all of its variables at once before delivery. If there are numerous parameters or various details that require confirmation, it can become quite complex.
- During development, testing, or demonstrations, it is not possible to recycle a service instance and preserve the service's configuration for future reuse without the need for reconfiguration.
I believe that we need support for service draft and resource recycle to resolve these problems.

**Comment by linyinli** [comment]
For more valuable use cases, such as rapidly setting up multiple environments for various tests within resource constraints, we need to enhance the service draft by introducing the capability to clone the draft only or clone and deploy simultaneously, regardless of whether the source of the clone is a draft or has already been deployed.

**Comment by Finenyaco** [comment]
Verified in main d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d.
