### ISSUE TITLE
Fail to create service when project & global templates share the same name

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1329]
**Steps to reproduce**
1. Add `https://github.com/walrus-catalog` catalog to the default project
2. Create a webservice

**Result**
Pop the error `model: template_version not singular`

**Environment**
- Walrus version: main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 9c5ea546b1918a53aaf1a3173a5f43b10dd5fe3e
- UI version: dev-19c51ab

**Test Result:** pass

No error returned.
<img width="1697" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f808a5ed-3b67-4e6f-9bbd-241b9b03dad8">
