### ISSUE TITLE
Support adding templates in a subdirectory

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1339]
e.g., https://github.com/terraform-aws-modules/terraform-aws-cloudwatch/tree/master/modules/cis-alarms.

**Comment by gitlawr** [comment]
Only apply to isolated templates, not for templates from a catalog.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 3ccf6b03dc821e799b35b45d41e07165821beb7f
- UI version: dev-e291910

**Test Result:** pass
<img width="2492" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d60ed072-231b-4e28-ba25-c5b5ac69d4a5">
<img width="1371" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f6d4531e-eb31-4b67-b148-d0d1a1ed6320">
