### ISSUE TITLE
Update naming of templates imported from a catalog

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1340]
**Is your enhancement related to a problem? Please describe.**
Improve readability of imported templates.

**Describe the solution you'd like**

For templates imported from a catalog, generate template name as `<catalog-name>/<template-name>`. Trim "terraform-" prefix if it is present in the repository name.

For example, 
`github.com/terraform-aws-modules/terraform-aws-rds` from catalog `aws-modules` results in `aws-modules/aws-rds`

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:** pass


<img width="2436" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b9ca3d66-ed50-4127-9ca7-fa51fd6bed1a">
<img width="2412" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e64c9607-6a28-475d-a495-0daf911b86bc">
