### ISSUE TITLE
Add built-in redis templates

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1341]
Add redis templates backed by kubernetes/aws/alicloud.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Test Result:**

- [terraform-kubernetes-redis](https://github.com/walrus-catalog-sandbox/terraform-kubernetes-redis)
- [terraform-alicloud-kvstore-redis](https://github.com/walrus-catalog-sandbox/terraform-alicloud-kvstore-redis)
- [terraform-aws-elasticache-redis](https://github.com/walrus-catalog-sandbox/terraform-aws-elasticache-redis)
- [terraform-static-redis](https://github.com/walrus-catalog-sandbox/terraform-static-redis)

Issues:
1.  Deployment fails if you don't fill in the password. https://github.com/seal-io/walrus/issues/1475
2. Failed to deploy alicloud/aws redis if you don't delete the `Domain Suffix` in UI schema. Same reasons as above.
3. Failed to deploy the aws redis using the default value `cache.t2.micro` of `class` field.
<img width="1520" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/28d0a0c4-1fca-415a-ad93-789631f04e78">

**Comment by gitlawr** [comment]
[kubernetes-redis]
The requirements for password is 16-32 chars but if you don't input one the generated password is 10 chars.

**Comment by gitlawr** [comment]
[alicloud-redis]
Enabled `Publicly Accessible`, but cannot connect to the address.

**Comment by gitlawr** [comment]
- [x] kubernetes redis
- [x] static redis
- [x] alicloud redis
- [x] aws redis

Verified in main.
