### ISSUE TITLE
Switching between Filled and Not Filled options on service details page causes the filter to malfunction

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1344]
**Describe the bug**

Switching between Filled and Not Filled options on service details page causes the filter to malfunction.

**Steps to reproduce**
1. Create a service.
2. Go to the service details page, expand the template configuration and switch between `Filled` and `Not Filled` options.

**Result**

1. The filter did not take effect after switching between the `Filled` and `Not Filled` options.
<img width="1695" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/320c785b-a763-478a-b781-4702ac15e0ad">

**Expected behavior**

The `Filled` and `Not Filled` filters can work.

**Environment**
- Walrus version: main 9c5ea546b1918a53aaf1a3173a5f43b10dd5fe3e
- UI version: dev-19c51ab

**Additional context**

**Comment by hibig** [comment]
Field filtering is not supported in new style form.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ce9f6f458d0e8facdc2448ccfe78b0ee434b301b
- UI version: dev-e0bc105

**Test Result:** The template configuration filters have been removed.

<img width="2466" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fda0b36c-96e2-46d3-9c52-4776593c3cac">
