### ISSUE TITLE
Update the help menu

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1354]
<img width="259" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/3d99ad2e-f7b7-472b-8dd1-a5b3ff48e476">

Change to:
- Report an Issue
- Join our Discord
- User Guide
- Version Info

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 4465aa8deb63ff1ceb270b6cbc1c5ae2852d8242
- UI version: dev-d246b6d

**Test Result:** Check the links: pass
<img width="756" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4e07e046-5ef5-41db-a8b6-ed93e22ef02f">
