### ISSUE TITLE
Optimize advanced options in workflows

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1367]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

1. Make the timeout field optional in workflow. No timeout by default.
2. Values can be customized.
3. Add a description to this field. There are different timeout options that may confuse users.

<img width="1487" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9fd0dbc9-9722-4235-ba26-87f865236f72">

<img width="1208" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/86ac8e91-0a0e-499d-bf23-a9f3413a5f18">

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.4.0-rc1  a3e5c0343d3e831ca30e4fd76a160212bc5bba7f
- UI version: dev-6b82ce8

1. The default value for parallelism is 10.
<img width="1446" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/19923a44-3e6d-4154-a2ae-b8f256dd673f">


2. No timeout or retry by default.
<img width="1202" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f8931409-bf35-44ed-854a-0bce673e144c">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 3ccf6b03dc821e799b35b45d41e07165821beb7f
- UI version: dev-e291910

**Test Result:**  Let's create the service step with no timeout by default.
<img width="1201" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ececa45f-6a22-4299-a7b1-e9804c33aadd">

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2 
UI version: v0.4.0-rc2

**Test Result**: Pass

<img width="1185" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/e1291be1-e80e-40f4-b6c7-08ce5eaf50a9">
