### ISSUE TITLE
Support for stop running workflows and deleting records

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1374]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

Currently, it can not abort running workflows and delete records.

<img width="2501" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/46ebc7a7-d7f0-40d2-a353-7d240e5a97a5">

**Describe alternatives you've considered**

**Additional context**

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2
UI version: v0.4.0-rc2

**Test Result**: pass
