### ISSUE TITLE
UI schema hidden not work for object

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1376]
**Steps to reproduce**
1. add hidden: true to an object variable in the schema.yaml
2. create a template based on that template
3. check the rendered UI
4. the hidden does not work
<img width="1468" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/481a40ff-6c5a-4493-926a-b35d9ac4a4d5">

**Expected behavior**
Should hide the variables.

**Environment**
- Walrus version:
https://github.com/seal-io/walrus/commit/065ee92e55e14044fa0777be4c631f7082fadc0e
**Additional context**
UI version: dev-b9a6538

**Comment by gitlawr** [comment]
<img width="615" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/75c29111-00db-42ad-adb2-c35d9981f94c">

hidden property is set in schema.yaml, but not shown in uischema

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.4.0-rc1  a3e5c0343d3e831ca30e4fd76a160212bc5bba7f
- UI version: dev-6b82ce8

**Test Result:** pass
