### ISSUE TITLE
[CLI] Should not should maxprocs log in cli

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1405]
**Is your enhancement related to a problem? Please describe.**
<img width="1058" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/5cf1ba31-47bf-4ef5-b174-8e7382f6f324">

We use maxprocs package, it will always show init logs, should not show these logs while use cli.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2 https://github.com/seal-io/walrus/commit/af772a7ae049670658fdb2d2249cfde51277db8e

**Test Result**: pass


![Image](https://github.com/seal-io/walrus/assets/45061862/0533b582-b68d-4a36-bc55-16987fddf554)
