### ISSUE TITLE
Fail to use output values of other services/resources

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1407]
**Steps to reproduce**
1. Create svc1 and db1 in the env
2. Create a new service using the webservice template, set foo=${resource.db1.some_output} in envvars.
3. Create another one with foo=${service.svc1.some_output}

**Result**
1. The one using `${resource.db1.some_output}` failed
2. The one using `${service.svc1.some_output}` succeeded, but there's no hints to help the input in the UI.

**Expected behavior**
Be able to reference service outputs with `${service.svc1.some_output}`
Be able to reference resource outputs with `${resource.db1.some_output}`

**Environment**
- Walrus version: v0.4.0-rc1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 4465aa8deb63ff1ceb270b6cbc1c5ae2852d8242
- UI version: dev-7b0f2a2

**Test Result:**
1. Use output values of other services/resources successfully.
<img width="766" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f8cde133-2019-4431-9112-76f072661bf3">

2. But there's no hints to help the input in the UI when referencing output variables of resources/services.
<img width="1229" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6ce4516c-1af6-426d-bdbf-5c28abe0c511">
<img width="1239" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/2a11d0db-2257-4632-bd6f-045b5f78ae6c">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 6eafc9f0ef146f3559f5b6469df2d2c4ca90e1fe
- UI version: dev-e291910

**Test Result:** pass
