### ISSUE TITLE
UI schema won't be updated after changing the resource definition rules

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1410]
**Describe the bug**

**Steps to reproduce**
1. Create a resource definition and add two rules (add webservie and rds tempaltes).
2. Check the UI schema.
3. Delete the webservice template rule and save.
4. Check the UI schema.

**Result**

1. The UI schema was not updated after deleting the rule.
<img width="2501" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/58ea5b26-cf16-4cfe-bc60-28cb59ab46c6">

**Expected behavior**

1. The UI schema will be updated after changing the rules.
2. If the user has modified the UI schema, a reset is required to update the UI schema.

**Environment**
- Walrus version: v0.4.0-rc1  a3e5c0343d3e831ca30e4fd76a160212bc5bba7f
- UI version: dev-6b82ce8

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.4.0-rc2 f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: v0.4.0-rc2

**Test Result:**
Create a resource and then change the template to another, the UI schema will not be updated.

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2
UI version: v0.4.0-rc2

**Test Result**: Pass

<img width="1284" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/81e0d77d-646b-4cd5-98d8-5f7d75ecd3c9">
