### ISSUE TITLE
Incorrect deployment statistics on dashboard

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1413]
**Describe the bug**

Deployment block of dashboard does not show statistics

**Steps to reproduce**
1. Create some services or resources.
2. Go to Dashboard and check the statistics. 

**Result**

1. Didn't display the deployment statistics.
<img width="2470" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/36eb10ec-bf9f-4b8f-a390-f74c89371d0a">

2. The latest 10 service list and the latest 10 resource list are the same.

**Expected behavior**

Show the statistics of deployment.

**Environment**
- Walrus version: v0.4.0-rc1  a3e5c0343d3e831ca30e4fd76a160212bc5bba7f
- UI version: dev-6b82ce8

**Additional context**

**Comment by gitlawr** [comment]
<img width="1375" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/7f68cb22-2670-4db9-bbde-5943d9bb4e19">
Should be fixed in the UI

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 14cd3f8fb0b4028913755cb07364bf4ace803797
- UI version: dev-830c6bb

**Test Result:** failed

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 4465aa8deb63ff1ceb270b6cbc1c5ae2852d8242
- UI version: dev-d246b6d

**Test Result:** pass

<img width="2501" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ba6025f6-ab62-4f89-9008-98f02d43d34a">
<img width="2425" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/96a8fc52-f24e-4959-be06-6b28ea0f7ede">
