### ISSUE TITLE
Wrong API call for get k8s storageClass

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1417]
**Steps to reproduce**
1. config the ui schema, use the widget StorageClassSelect
2. check the UI
3. check the API call is `https://localhost/proxy/api/v1/storageClasses?connectorID=486645474749592093`
4. check the response, which means the api call is wrong
<img width="1219" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/4e71e105-34d1-4620-ad84-8e06d78b27df">

**Result**

**Expected behavior**
From the doc, should use this api https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/#list-list-or-watch-objects-of-kind-storageclass

**Environment**
- Walrus version: a3e5c0343d3e831ca30e4fd76a160212bc5bba7f

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: a3e5c0343d3e831ca30e4fd76a160212bc5bba7f
- UI version: dev-61bd325

**Test Result:** pass

Check the api request: 
`https://x.x.x.x/proxy/apis/storage.k8s.io/v1/storageclasses?connectorID=487061225604120578`

Check the response:
<img width="859" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c2b5cd0e-4ef8-4b3e-9c0a-d3cf574b3ed7">

Check the widget:
<img width="1231" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/805c5a3f-5f3a-4844-b00a-6cb881659138">
