### ISSUE TITLE
UI issues for resource

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1424]
1. View a resource definition, it shows uiSchema tab by default.(why not show the first tab?)
2. Create a resource, it shows `New Resource Definition` in breadcrumb.
3. Create a resource, it shows `Template Configuration`.
4. Create a resource definition and set UISchema to empty variables. Create a resource. Should we remove Configuration block when it's empty?

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 14cd3f8fb0b4028913755cb07364bf4ace803797
- UI version: dev-830c6bb

**Test Result:** 
1. pass
2. pass
3. pass
4. pass
<img width="1615" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c26f774f-453c-4b51-9993-e715498c66ec">
