### ISSUE TITLE
UI issues for workflow

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1425]
1. Create a workflow, it shows `Workflow ID`. change it to `name` to keep consistency with the rest of the product.
2. Create a workflow, change timeout unit from hour to minute, which is more practical.
3. Create a workflow, Change `Add Task` to `Add Step` to keep concept consistent. Update other UI parts as well.
4. Create a workflow, the stage name defaults to `stage` in zh, defaults to `New Stage` in en. Make it consistent and recommend using something like `Stage-1` as the default to differentiate stages.
5. Create a workflow step, change `Create Task` step type to `Deploy Service`.
6. Add deploy service step, 
<img width="789" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/c3cab6fe-4ed9-4ef8-bc1f-f45b6d8f5047">

7. Add deploy service step, there's no any hint telling users it's a service configuration.
<img width="1177" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/77b63de6-7749-4cf9-91e0-9cd31ba733a2">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 3ccf6b03dc821e799b35b45d41e07165821beb7f
- UI version: dev-e291910

**Test Result:** 
Please change other `task` to `step` too.
<img width="333" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9ba24e82-3096-4d2b-9fc7-aadac06fc148">
<img width="1201" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/06ccac07-c156-4d9f-b644-0a7ef0065f11">

<img width="1200" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/cf464a00-b00d-4168-a66d-ed8310aca7d8">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.4.0-rc2 f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: v0.4.0-rc2

**Test Result:** pass

<img width="1195" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fb7828f5-c786-45b7-8a4a-3c0b698cd72e">
<img width="1181" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3888a7be-522b-4ac9-8279-82066f6002da">
<img width="653" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b6e5ad6c-303e-4a5b-9ab7-7fe2ff6d03fe">
