### ISSUE TITLE
Add more details when rolling back a service or resource

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1445]
**Is your enhancement related to a problem? Please describe.**
When rolling back a service or resource, only the timestamp and diff are showed when selecting a revision. We cannot get more information such as revision details or who generated the revision. I suggest it should  include more details when rolling back.

**Describe the solution you'd like**
1. Add an optional comment when deploying a service or resource, and record both the comment and the operator's information in the revision.
2. Show the comment and the operator's information when rolling back a service or resource.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Test Result:** pass

<img width="766" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f2b71915-dada-46ba-ad37-bd6e6f29dc36">
