### ISSUE TITLE
Incorrect button status on workflow details page

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1452]
**Describe the bug**

**Steps to reproduce**
1. Run a workflow.
2. Stop the workflow

**Result**

1. Unable to stop a running workflow, the stop button is grey.
<img width="2484" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/592e965c-79b6-4802-9f9d-55006d437585">

2. But it can be clicked on `Retry` when the workflow is running.

**Expected behavior**

1. Stop when it is running.
2. Retry when it is completed.

**Environment**
- Walrus version: 3ccf6b03dc821e799b35b45d41e07165821beb7f
- UI version: dev-e291910

**Additional context**

**Comment by shanewxy** [comment]
**Environment**: dev-a1ddf00
**Test result**: pass

![Image](https://github.com/seal-io/walrus/assets/45061862/e9c5ac45-e7cd-439f-983b-ebda4b18edef)


![Image](https://github.com/seal-io/walrus/assets/45061862/8dcc41a8-115e-40a1-9f71-4275b58ba201)
