### ISSUE TITLE
UI Issue: improve consistency in naming scheme of tables

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#1455]
Tables are extensively utilized in the Walrus. Currently, there are inconsistencies in the naming scheme of the first column of tables. The first column is the object's name attribute in most cases. We have set the column name as either 'object type', 'object type + name' or 'name' currently. 

For example, the first column of Catalogs is 'Catalog Name' in Operation Hub. But in connectors and other tabs, the first column is 'Connector' instead of 'Connector Name' or 'Name'. The same problem is in environment level and Chinese UI. To enhance overall coherence throughout the product, it is advisable to establish consistency in this aspect. 'Name' or 'Object type + name' may be a better choice based on the practices of other products. 

![image](https://github.com/seal-io/walrus/assets/16434640/495e63a1-b5b8-47da-b99b-6477a87a8b08)

![image](https://github.com/seal-io/walrus/assets/16434640/6bd79e5d-34e2-4054-86fb-0ce3e418c5d7)

After this, we need to pay attention to the consistency of the search hint. Currently, there are also inconsistencies as below. Some contain 'a' or 'an' but others don't. It seems we only support filter by name, we can just use ’Filter by name' in English and '名称搜索' in Chinese as hints.  

<img width="779" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/21abd6c5-51dc-44b0-aeeb-b9f2137b8156">
<img width="863" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/96aa7ed9-4e40-4a9d-8a28-db38d39f8b52">
<img width="1171" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/e22063c2-14a6-4f0b-ab8f-0b4e7caa4eb3">
<img width="344" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/e887706e-8039-48ba-b202-5c23a1c5de76">

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2 
UI version: v0.4.0-rc2

**Test Result**: pass

<img width="1429" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/04774ba2-d171-4e27-8094-ca43a303763e">
<img width="1424" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/91725be1-c00c-4f6c-b3d0-c2be2a0db8be">
<img width="1433" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/ec38c214-04fc-4a00-929e-deae12258980">
<img width="1448" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/a2dc7566-2057-4f9d-b881-bb375a21746e">
