### ISSUE TITLE
UI Issue in v0.4-rc1: misleading or grammar related - part I

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#1460]
1.  The "contains only lowercase alphanumeric or "-", starts with an alphanumeric and ends with an alphanumeric” should be changed to "Contains only lowercase alphanumeric or "-", starts with an alphanumeric and ends with an alphanumeric.", capitalize the first character and add a full stop. The same problem exists in almost all "New xxx" pages.

<img width="583" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/0e32262e-909f-497a-88fd-385af19541b0">

2. User Center -> User Inofomation -> Modify Password, "Confirm New password" should be "Confirm new password".

<img width="497" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/c0f7a85b-719d-4d0d-abf1-d1fc7877e423">

3. Dashboard -> Deployments, the title "Latest 10 Service" and "Latest 10 Resource" are inaccurate and have grammar issues (plural) , which should be "Latest 10 Service Deployments" and "Latest 10 Resource Deployments". 

<img width="1302" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/b0995d9d-7f4b-4f26-b9f9-818ed7f8b2ca">

4. Dashboard -> Deployments, the "CreateTime" should be "Create Time"

<img width="1294" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/ef9f763b-14f3-4beb-bdf5-d0740bb047e0">
 
5. User Center -> User Information -> System Permissions, the "UI Permissions" should be "Permissions" as they are not just "UI" permissions. The "界面权限“ should be changed to "权限" in Chinese UI.

<img width="1351" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/8065d4ae-352a-4334-aa05-d26f571c5fc7">

6. System Settings -> Deployment Management -> NO_PROXY. The hint should be changed from "list of IPs、domain name with ',' separated" to "List of IPs and domain names with "," separated". There is no “、" sign in English and domain name should be in plural format as well. The Chinese version should be changed from "逗号分割的IP列表、域名列表，支持模糊匹配；例：192.168.0.*,*ip.net" to "逗号分隔的IP列表、域名列表，支持模糊匹配；例如：192.168.0.*,*ip.net" 

<img width="546" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/40163401-d502-4f63-a0df-379ae6452cb4">

7. Operation Hub - Templates, click the "..." button of template. The "Set as Service Available Template" and "Cancel Service Available Template" can be changed to "Enable for Service" and "Disable for Service", which may be more concise. The Chinese could be "为服务启用/为服务停用” or even "服务启用/服务停用"。 

<img width="941" alt="image" src="https://github.com/seal-io/walrus/assets/16434640/6ac27c38-73c3-4b11-b051-a27d710ae567">

**Comment by alexcodelf** [comment]
Environment

Walrus version: v0.4.0-rc2 https://github.com/seal-io/walrus/commit/f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
UI version: v0.4.0-rc2

Test Result:  Failed
1.  issue one
<img width="790" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/3aa07999-975e-4fad-b2eb-04e58f93ec45">
2. issue two
<img width="1129" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/3443ac8a-97f5-47e4-a9a8-a26e052a7b63">
3. issue three
<img width="2136" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/3a1d34b8-973f-464d-a6a3-a480aa9cabc4">
4. issue four
<img width="1478" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/cb08503c-ef6b-4f0c-82ec-f56144570e29">
5. issue five
<img width="2966" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/1a17f6f9-b61f-41d3-9050-34a7e3d71b33">
<img width="2926" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/0beb0378-84ce-409f-982e-2124392ee66b">
6. issue six **Failed with a misspell of and**
<img width="983" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/89e862f0-7576-4fc3-8f4d-ed3beacf7381">
7. issue seven 
<img width="2478" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/72c631ff-7fcf-4a67-9849-f52c62708ba0">

**Comment by alexcodelf** [comment]
@hibig Please fix issue 6

**Comment by alexcodelf** [comment]
Issue 6: PASS.

Env: walrus-ui: de56cd1

![Image](https://github.com/seal-io/walrus/assets/85595852/1599db04-42d1-439f-8935-e74141820611)
