### ISSUE TITLE
Service draft cannot be saved as a draft again after the first save

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1461]
**Describe the bug**
Service draft cannot be saved as a draft again after the first save.

**Steps to reproduce**
1. Go to 'Projects-Environments-Services/Resources' ,create a service and save as draft;
2. Edit the service draft and save as draft again.

**Result**
It will be deployed automatically.

**Expected behavior**
Service draft can be saved as a draft again.

**Environment**
- Walrus version: v0.4.0-rc2

**Comment by alexcodelf** [comment]
Env: walrus-server: 89cdec08768c3a8ed0dbf1490e04f03ad3ecf630
Result: PASS. Draft resource can be saved as a draft again.
<img width="2922" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/f01c4b47-738d-4d12-b083-a442dcddba42">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 1f87819b63d844001b3353645ed96d110406783c
- UI version: dev-71a5388

**Test Result:**

This issue can be reproduced in main.

<img width="2444" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ce9825ac-6646-4d9b-b9fe-32290f24f98a">


```
2024-03-06T11:53:59.563Z	E	api	error requesting PUT /v1/projects/503645663356034050/environments/503645663356034050/resources/503646001031060482/upgrade: 1 error occurred:
	* cannot save resource "draft" as draft: in "" status


github.com/seal-io/walrus/pkg/apis/runtime.erroring
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_error.go:45
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/seal-io/walrus/pkg/apis/runtime.recovering
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_recovery.go:39
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/seal-io/walrus/pkg/apis/runtime.observing
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_observation.go:89
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
github.com/seal-io/walrus/pkg/apis/runtime.(*Router).ServeHTTP
	github.com/seal-io/walrus/pkg/apis/runtime/router.go:194
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.initALPNRequest.ServeHTTP
	net/http/server.go:3546
net/http.(*http2serverConn).runHandler
	net/http/h2_bundle.go:6193
2024-03-06T11:53:59.563Z	D	api	500 | HTTP/2.0 |     1016 B |       96 B |   54.913778ms |   192.168.156.1 | PUT     /v1/projects/503645663356034050/environments/503645663356034050/resources/503646001031060482/upgrade
```

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 96792e2d3b2c3b1eae368faeb3c2690f91fbffc5
- UI version: dev-040e825

**Test Result:** pass
