### ISSUE TITLE
Cannot edit the service while it is stopped

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1462]
**Describe the bug**
Cannot edit the service while it is stopped.

**Steps to reproduce**
1. Go to 'Projects-Environments-Services/Resources', create a service;
2. Stop the service;
3. Try to edit it.

**Result**
Cannot edit the service while it is stopped

**Expected behavior**
Can still edit the service when it stops.

**Environment**
- Walrus version: v0.4.0-rc2

**Comment by gitlawr** [comment]
Pending on UI changes in https://github.com/seal-io/walrus/issues/1473 before testing

**Comment by gitlawr** [comment]
Verified in main
