### ISSUE TITLE
Deploying the service fails when started in the environment list if the service annotation is empty

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1470]
**Describe the bug**

**Steps to reproduce**
1. Clone an environment and save as draft.
2. Start the service in service list.
3. Stop the service in environment list.
4. Check the deployment results.

**Result**

1. Failed to apply resource: subject id is empty.
<img width="1589" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6442207d-e131-4f90-81fa-599343d8e1f7">

2. Check walrus logs.
```
2023-11-19T15:14:28.515Z	D	api	200 | HTTP/2.0 |        0 B |     11 KiB |    2.621682ms |   192.168.247.1 | GET     /v1/projects/488007629784807170/environments/488009282005038850/resources/488010955498780418/revisions/488011075522983682/terraform-states
2023-11-19T15:14:30.026Z	E	resource	failed to apply resource: subject id is empty
github.com/seal-io/walrus/pkg/resource.Apply
	github.com/seal-io/walrus/pkg/resource/resource.go:102
github.com/seal-io/walrus/pkg/scheduler/resource.(*RelationshipCheckTask).deployResource
	github.com/seal-io/walrus/pkg/scheduler/resource/relationship_check_task.go:230
github.com/seal-io/walrus/pkg/scheduler/resource.(*RelationshipCheckTask).applyResources
	github.com/seal-io/walrus/pkg/scheduler/resource/relationship_check_task.go:123
github.com/seal-io/walrus/pkg/scheduler/resource.(*RelationshipCheckTask).Process
	github.com/seal-io/walrus/pkg/scheduler/resource/relationship_check_task.go:77
github.com/seal-io/walrus/utils/cron.timeoutTask.Process
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/cron/cron.go:156
reflect.Value.call
	reflect/value.go:584
reflect.Value.Call
	reflect/value.go:368
github.com/go-co-op/gocron.callJobFuncWithParams
	github.com/go-co-op/gocron@v1.29.0/gocron.go:116
github.com/go-co-op/gocron.runJob
	github.com/go-co-op/gocron@v1.29.0/executor.go:76
github.com/go-co-op/gocron.(*executor).runJob
	github.com/go-co-op/gocron@v1.29.0/executor.go:173
github.com/go-co-op/gocron.(*executor).run.func1
	github.com/go-co-op/gocron@v1.29.0/executor.go:239
```

3. Check resources table. The annotation is empty.
<img width="1660" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4ce691dd-66c5-4c7a-b9ac-527afa8a6875">

4. Upgrade services can be deployed successfully, but the deployment fails when it is started in the environment list. And deploy a service without subject id is hard to reproduce.

**Expected behavior**

1. Deploy successfully.

**Environment**
- Walrus version: v0.4.0-rc2 f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: v0.4.0-rc2

**Additional context**

**Comment by gitlawr** [comment]
Hard to reproduce, needs further investigation.

**Comment by gitlawr** [comment]
Cannot reproduce

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Test Result:** Cannot reproduce in the latest three versions.
