### ISSUE TITLE
Incorrect status of the Stop/Start button in the service list

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1471]
**Describe the bug**

**Steps to reproduce**
1. Create a service.
2. Go to service list, select the service and click on the `...` icon  in the operation column.

**Result**

Issue 1: The `Stop` button is grey out when the service is in the Ready state,.
<img width="2480" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/322985a9-1cc4-4626-8bf5-26863af09ab8">

Issue 2: When the button is greyed out, the click still works.

**Expected behavior**

Issue 1: When the service/resource is in Ready state, it can be stopped.
Issue 2: When the button is greyed out, clicking on it is not responding.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-e4baff9

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

Service in Deploying state is not stoppable.

<img width="2519" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3fc1fa94-f04d-4b86-a35d-548953e760c8">

**Comment by shanewxy** [comment]
**Environment**

UI version: 0.4.0-rc2

**Test Result**: Pass

<img width="1374" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/b51bd3b4-7fee-42ee-8762-8c37dfaafe93">
<img width="1382" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/351f953e-7b30-4367-b43d-d301da591e56">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8fc1ee8f23f152bbeaf1aec685c03d15ffbccae1
- UI version: dev-d9eaece

**Test Result:** Cannot stop a service in `NotReady` state.

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/adcbe76c-7a27-46e3-a631-640a51ae3efc">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ee6f73576bbb364db67bd41edb1ba2b148a6710e
- UI version: dev-f5933d5

**Test Result:** pass

<img width="1673" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c4677b0f-1bf3-4ec1-b370-b57f5e7ab616">
