### ISSUE TITLE
Issues for saving resources/services

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1473]
**Describe the bug**

**Steps to reproduce**
Issue 1: New a service/resource.
Issue2: Create a service and then upgrade it.

**Expected behavior**

Issue 1: Make the default option as `Save and Deploy` when creating a service/resource.
<img width="2495" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0127d8ce-8faa-4217-8171-8af6faf3b8c3">

Issue 2: A service/resource that has been deployed once, regardless of its state, cannot be saved as a draft.
<img width="2508" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/11cf3552-7ce3-4a96-9af3-5460ab30c6e7">

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-e4baff9

**Additional context**

**Comment by Finenyaco** [comment]
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-c05317a

**Test Result:** 
A service/resource that has been deployed once cannot be save as draft. Please remove the options when upgrade the services.
<img width="1042" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1e2b2bd0-1e4c-4793-9ed8-e575a4b297ed">

**Comment by gitlawr** [comment]
Per discussion, let's provide "Save and Deploy"/"Save Draft" for inactive(undeployed/stopped) resources, and provide no "Save Draft" action for other cases

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2 
UI version: v0.4.0-rc2

**Test Result**: Pass
