### ISSUE TITLE
When the default value is null, an empty string is sent

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1475]
**Describe the bug**

**Steps to reproduce**
1. Add a template with source `https://github.com/walrus-catalog-sandbox/terraform-kubernetes-redis?ref=main`.
2. Enable the template for service.
3. New a service using the template above without filling in the password field.

**Result**

1. Failed to deploy. Returned an error `Invalid password`.
<img width="1038" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/41035db1-3dd8-44e3-a5b2-c0726182c3f5">

2. Check the api request. It should send the password field.
<img width="845" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/12dfe71c-e0fa-415f-96b7-65f9df5a6869">

**Expected behavior**

Deploy successfully.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-e4baff9

**Additional context**

**Comment by alexcodelf** [comment]
Env:  walrus-ui: 4874eff
Result: PASS. Can set password when create or update the service.

<img width="2969" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/34a3e7ec-9fb2-42e6-829b-110c15892ff3">
<img width="2991" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/cf973b24-04b4-40de-b354-2f9ca070a0e9">
