### ISSUE TITLE
Cannot preview the changes after editing template UI schema

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1477]
**Describe the bug**

Cannot preview the changes after editing template UI schema

**Steps to reproduce**
1. Go to 'Operation Hub -> Templates', go the a template's details page and click on the 'UI schema' tab.
2. Modify the schema and preview.

**Result**

1. Do not show the changes until you click Save.

**Expected behavior**

1. It can preview the changes after editing.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-e4baff9

**Additional context**

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2 af772a7ae049670658fdb2d2249cfde51277db8e
UI version: v0.4.0-rc2

**Test Result**: pass

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 0bde30233f43610dfcdcdaa3d925982fb461f07b
- UI version: dev-375fc54

**Test Result:** Reproduced in main.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 0ce7516077eac143abadf67373426215f867d593
- UI version: dev-90d701d

**Test Result:** pass
