### ISSUE TITLE
Issues for service forms

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1478]
**Describe the bug**

**Steps to reproduce**
Issue 1:
1. New a service using `webservice` template.
2. Delete the value of `Ports` field.
3. Reconfigure `80` in `Ports` field.

Issue 2: 
1. New a service using a template with a variable containing an enum field.
2. Select a value and then delete it.

**Result**

Issue 1. Failed to reconfigure `80`.
<img width="1956" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1e19f2ba-abc9-486a-b221-f1e7d959b68c">

Issue 2: Cannot delete the value.
<img width="1257" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/424e414f-24e9-4b41-a978-b8386493e452">

**Expected behavior**

Issue 1: Reconfigure default value successfully.
Issue 2: Selected values can be deleted. Because this variable may be optional rather than required.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Additional context**

**Comment by gitlawr** [comment]
Issue 2: Passed.

Issue 1: Failed.


Remove the default 80 port, then click the dropdown, there's the 80 option which is odd.
<img width="1431" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/9eb62031-b62d-4b5e-92f2-4047dafad2e8">

Select 80 port again, then save. it's not set in the service attributes

<img width="1371" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/9cca8004-8fb7-4af8-b7db-49897845d055">

**Comment by gitlawr** [comment]
Validation failed on UI version dev-9a14b70

Configured ports are still missing.

**Comment by gitlawr** [comment]
Validation failed on UI dev-de56cd1

It sets two ports in hybrid number and string format.
<img width="1330" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/b648dd7f-c45e-42ed-bf1a-19e318c9eeec">

Given schema is a number array
<img width="554" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/9a29d930-d77f-4f19-b67a-61887431399c">

**Comment by alexcodelf** [comment]
Env: UIdev-7e7c81a

Issue 1: PASS

1. create a new service using `webservice`
2. delete value of `Port` field
3. add value of `Port` field.

Result: successfuly create a new service with multi ports

![Image](https://github.com/seal-io/walrus/assets/85595852/9e3a78ec-f8f3-455d-a98a-ebb3b69a43f9)

**Comment by alexcodelf** [comment]
Env: UIdev-7e7c81a

Issue 2: Failed

The single dropdown form field value can not be cleared.

https://github.com/seal-io/walrus/assets/85595852/2bc8e0dd-dbff-4d73-accf-c42f1b7e86f6

**Comment by alexcodelf** [comment]
> Env: UIdev-7e7c81a
> 
> Issue 2: Failed
> 
> The single dropdown form field value can not be cleared when press delete button.
> 
>  2023-11-23.15.04.25.mov

After careful and detailed discussion, we have determined that the enumeration type form control is mandatory, hence the option values **cannot** be cleared and one must be selected from the available options.

Issue 2 is not a bug.
