### ISSUE TITLE
Viewing template detail page sometimes returns an error: model: template_version not found

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1481]
**Describe the bug**

Viewing template detail page sometimes returns an error.

**Steps to reproduce**
1. Add a project template.
2. Go to the template detail page.

**Result**

1. Sometimes it will return an error message: `model: template_version not found`.
<img width="2542" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d381f89f-77f6-4b90-bf16-de50cad73b80">

2.  Check the api request.
<img width="725" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f75cf4e2-8d5c-4990-877c-2a044e80141f">

3. The correct api request is as follows:

<img width="936" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/130e9af7-e248-4ed7-934a-09c9803c6027">

**Expected behavior**

No error returned.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Additional context**

**Comment by gitlawr** [comment]
Not consistently reproducible, needs further investigation

**Comment by linyinli** [comment]
The same problem is encountered, and the corresponding template version can be queried in the database:
<img width="1752" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/1a0dda4d-58e7-4902-bbc6-0d577b81c56d">
<img width="706" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/e8a6cf3c-b7be-47f8-a6a8-397e412828c6">
<img width="602" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/568133b8-5764-4d97-88af-bc47830daa68">
Seems to be a path error, the correct path is:
<img width="1919" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/d4c91b28-ee13-4d66-86ee-e3df619e08d9">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8fc1ee8f23f152bbeaf1aec685c03d15ffbccae1
- UI version: dev-199faf2

**Test Result:** pass

Get template details before getting template version now. Cannot be reproduced in dev.

<img width="1021" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/11b0539d-d8f8-4f7b-9364-2d58691bbda2">
