### ISSUE TITLE
Environment variable values are not displayed when upgrading services

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1483]
**Describe the bug**

**Steps to reproduce**
1. Create a service using `webservice` template with env variables.

<img width="2459" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0e1e2148-5014-4fb8-bcce-602f38ac4242">

2. Upgrade the service.

**Result**

1. Didn't show the value of environment varialbes.
<img width="2487" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6ee5f1a8-04ba-4ce9-adfc-489e458f8b3f">

2. Check the GET resource api response. 
<img width="958" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a71ad1dd-0c2e-4b6b-ab55-f47a7246a824">

**Expected behavior**

Display all configured values.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-9a85369

**Test Results:**
1. Create two services using `webservice` template.
2. Clone these two services. Edit the environment variables of one of the services. 
3. Check the environment variables of the other service. Show the same environment variables

**Comment by gitlawr** [comment]
Verified in main
