### ISSUE TITLE
Skip importing archived templates

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1484]
When adding a catalog, skip archived repositories.

**Comment by alexcodelf** [comment]
Env: walrus-server: d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d
Result: PASS
Case: add a new catalog with archived repositories.

<img width="1261" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/a1d8e444-516b-44fe-a243-640211c60918">

Result: Archived template webservcie is not imported.

<img width="1403" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/f3800992-c9a1-4e23-8157-5445baf4e66f">
