### ISSUE TITLE
Cannot stop the service dependencies 

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1491]
**Describe the bug**

**Steps to reproduce**
1. Create some services.
2. Make some services dependent on others, for example:

<img width="758" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/dbfe582d-ab56-4acd-9606-7fe41cbdbb3c">

3. Go to environment list and click `Stop`.
4. Check the service status.

**Result**

Issue 1: Service dependencies were not stopped.
<img width="2491" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/97e73426-2015-4367-a658-81961c49683b">

Issue 2: Stop again, it cannot stop because some services are in stopped state.
<img width="982" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/034b9ad6-cd76-4a39-8073-6db9903ca152">

**Expected behavior**

Issue 1: Service dependencies can be stopped.
Issue 2: When some services are already in a stopped state, it is still possible to successfully stop the environment services.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Additional context**

**Comment by alexcodelf** [comment]
Env:  walrus-server: d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d
Issue 1:  PASS. service b depend on a can be stopped. 
<img width="2912" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/b3859e5e-d981-497f-96d9-33a729a26fdf">

Issue 2:  PASS.  some services are already in a stopped state, it can successfully stop the environment services.
    case: create service c, stop the env from step 1.
    result: service c can be stopped.
<img width="2934" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/37f01395-8bee-4902-b930-f0246f79acc9">
