### ISSUE TITLE
Add containerservice template

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1492]
A phased enhancement of https://github.com/seal-io/walrus/issues/1322

**Comment by shanewxy** [comment]
<img width="1410" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/6e88a28c-ce8e-44db-aa92-b43a64cc9c31">

**Comment by thxCode** [comment]
@aiwantaozi 
request payload
```
{"projectID":"488376810577343068","project":{"id":"488376810577343068","name":"default"},"environment":{"id":"488422047001621084","name":"testing"},"description":"","labels":{},"type":null,"name":"indexer","template":{"id":"488421664061665884","name":"terraform-kubernetes-containertask","version":"v0.1.0","schema":{"openAPISchema":null,"readme":"","requiredProviders":null},"uiSchema":{"openAPISchema":null},"template":{"id":"488421664044888668","status":{}}},"attributes":{"containers":[{"envs":[],"files":[{"mode":"0777","path":"/var/run/generate-data.sh","content":"#!/usr/bin/env bash\n\nitems=(foo bar baz qux xyz)\necho ${items[$JOB_COMPLETION_INDEX]} > /input/data.txt\n","content_refer":{"params":{},"schema":""}}],"image":"bash","mounts":[{"path":"/input","volume":"input","subpath":"","readonly":false,"volume_refer":{"params":{},"schema":""}}],"execute":{"args":[],"as_user":null,"command":["/var/run/generate-data.sh"],"as_group":null,"working_dir":"","readonly_rootfs":null},"profile":"init","resources":{"cpu":0.25,"gpu":null,"memory":256}},{"envs":[],"files":[],"image":"busybox","checks":[],"mounts":[{"path":"/input","volume":"input","subpath":"","readonly":false,"volume_refer":{"params":{},"schema":""}}],"execute":{"args":[],"as_user":null,"command":["rev","/input/data.txt"],"as_group":null,"working_dir":"","readonly_rootfs":null},"profile":"run","resources":{"cpu":0.25,"gpu":null,"memory":256}}],"context":{},"infrastructure":{"gpu_vendor":"nvidia.com"},"task":{"mode":"once","retries":6,"sysctls":[],"timeout":300,"completions":5,"parallelism":3,"cleanup_finished":false}},"id":"488512816488120583","createTime":"2023-11-23T02:18:48.952422Z","updateTime":"2023-11-23T02:32:00.070283Z","status":{"summaryStatus":"DeployFailed","error":true,"conditions":[{"type":"Deployed","status":"False","lastUpdateTime":"2023-11-23T02:19:35.593566Z","reason":""},{"type":"Ready","status":"True","lastUpdateTime":"2023-11-23T02:19:00.038759Z","reason":""}]}}
```

response payload
```
{
    "message": "invalid variables: invalid containers: Value is not nullable",
    "status": 400,
    "statusText": "Bad Request"
}
```

**Comment by thxCode** [comment]
@hibig 

<img width="892" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/85ead8ca-c4af-4022-8845-67b3c1341abb">

<img width="834" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/79d1d195-0ecc-4d6c-90fb-437e5834647e">

send a default empty object to the hidden field.

**Comment by thxCode** [comment]
@alexcodelf 

declare an entrypoint script via `files` content to use the Shell Environment Reference, like `${MYSQL_DATABASE}`, which causes failure deployment.

- the ${var/service/resource} reference parsing requires stronger anti-interference ability.
- for non-walrus reference logic, $ needs to be escaped to avoid run failure, see special escape sequences from https://developer.hashicorp.com/terraform/language/expressions/strings.

**Comment by thxCode** [comment]
> @hibig
> 
> <img alt="image" width="892" src="https://user-images.githubusercontent.com/3394724/285089523-85ead8ca-c4af-4022-8845-67b3c1341abb.png"> <img alt="image" width="834" src="https://user-images.githubusercontent.com/3394724/285089549-79d1d195-0ecc-4d6c-90fb-437e5834647e.png">
> send a default empty object to the hidden field.

@hibig I have made a change to avoid this https://github.com/walrus-catalog-sandbox/terraform-kubernetes-containerservice/commit/4795954304508a10e653e13903e0cf0c84caae04, but we still need to solve this before release.

- respect the minimum/maximum of number, the minLength/maxLength of string.
- nullable leaf property should have a clean button, for example, `a_string: ""` -> (clean) -> `a_string: null`.
- enum string property treats as a required attribute, even if we generate a null value for it at present.
- empty structure, aka. zero structure, reflected from the default values.
- before submission, clip the null fields that do not have default values. this may require some tree traversal operations.

BTW, do we have any OpenAPI defaulter or Validator libs to finish the above jobs?

**Comment by gitlawr** [comment]
DeployFailed when a containerservice uses envvar "foo=${service.mysql.password}".

**Comment by shanewxy** [comment]
Verified in main
