### ISSUE TITLE
Unable to run workflow if non-runtime configurable variables are configured

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1497]
**Describe the bug**

**Steps to reproduce**
1. Create a workflow and add a variable that does not enable runtime-configurable.
<img width="509" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/60007965-d587-4cfc-b89e-003b801f1f05">

2. Run the workflow.

**Result**

1.  Shows variables that can't be overwritten.
<img width="978" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/faa531db-5d91-4a84-87fa-df18189acb77">

2. Directly executed the workflow without filling in a variable value. Returned an error.
<img width="1740" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b1f3fc13-6515-403f-86b3-fcdd4431ac5e">

3. Filled in a value and then execute. Returned an error too.
<img width="1588" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ab9dc518-880e-4696-94bf-c9403c06022a">

4. Check GET workflow api response.

<img width="715" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f344bda9-62b8-4b29-ab96-89a8a4a9246f">

**Expected behavior**

Do not display the variables that can't be overwritten.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-c05317a

**Additional context**

**Comment by shanewxy** [comment]
**Environment**

Walrus version: v0.4.0-rc2
UI version: v0.4.0-rc2

**Test Result**: Pass
