### ISSUE TITLE
Classify inactive status in the API

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1500]
In resource API, we can tell if the status is in error or transitioning, but we cannot differentiate inactive status like stopped from active status like ready.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8fc1ee8f23f152bbeaf1aec685c03d15ffbccae1
- UI version: dev-199faf2

**Test Result:** pass

Inactive states include `Stopped` and `Undeployed`.

**Comment by gitlawr** [comment]
This issue is for clarifying inactive in the status of resource API like transitioning and error. Not for the statistics in environment list.

**Comment by gitlawr** [comment]
For UI: use a proper color for inactive resource/component status.
![image](https://github.com/seal-io/walrus/assets/5697937/0c8109cd-b8e7-4464-8fe1-1c1c52f9116e)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 278965251ef397a0f67ffab3c9348f4243d92c56
- UI version: dev-bb09fa3

**Test Result:** Failed

<img width="2450" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7a34f6ea-141d-4f06-8efa-650dea141037">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 38bbd2af03b5e73b87a803f864ab2045c79b9fe0

The inactive flag is missing when the docker container's state is "Exited".

<img width="2460" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/39bb468b-0af3-4fe0-9c7b-e79b1f403920">

<img width="976" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7252a73f-b76c-4aac-878b-5e779c8026ea">

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ef04d46a-8b70-4ef4-80bd-bf394a6070fb">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 3d6c9b2deb4970b456b6eff301c158e7543645db
- UI version: dev-6581d77

**Test Result:**
- Environment list page: failed 
<img width="2394" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3018b79d-d51f-45c2-962c-e3ac6e01d6dd">

- Resource details page: pass
<img width="2437" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a7bc892a-dc5a-427c-855d-eb1bdbc38a35">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 1e59b4feaae335bfa20cbfa170908396806ca7b5
- UI version: dev-437b352

**Test Result:**
- UI: pass

<img width="2409" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5e14c3da-f903-4d87-899f-c05feb80566d">

- Track the color of `Exited` status in https://github.com/seal-io/walrus/issues/1857.
