### ISSUE TITLE
Overwrite user configuration by default values when editing services

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1506]
**Describe the bug**

**Steps to reproduce**
1. Create a service using `webservice` template.
2. Edit the service, delete the value of `CPU Request` and `Memory Request` and save.
3. Edit the service again, and check the configuration.

**Result**

1. It will display the default value.
<img width="1588" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6a70842c-1722-4c45-8e82-34c2d8e03561">

**Expected behavior**

Show user configuration.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-9a85369

**Additional context**

**Comment by gitlawr** [comment]
Verified in main
