### ISSUE TITLE
Sometimes it will display two records after adding a connector/service/resource

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1507]
**Describe the bug**

Sometimes it will display two records after adding a connector/service/resource.

**Steps to reproduce**
1. Add a connector.

**Result**

<img width="2494" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a0cbb128-3f4c-49e6-a6ee-d9597df14973">

**Expected behavior**

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-9a85369

**Additional context**

**Comment by gitlawr** [comment]
Cannot find a consistent way to reproduce, needs further investigation

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ab30b62917ad1ab35c43d37fb7a646efbd9a1572
- UI version: v0.4.1-rc1

**Test Result:** pass
