### ISSUE TITLE
Create service form looks weird

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1511]
**Steps to reproduce**
1. Create a webservice

**Result**
<img width="1429" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/840fb1fb-8a82-473c-af8e-01ec43affc7e">
<img width="406" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/88deeb05-59ea-46d9-9022-74b94857a89a">

**Environment**
- Walrus version: main

**Comment by alexcodelf** [comment]
Env: walrus-ui [7e7c81aad24b7e9e0e8400bed962f2bc31a2ec67](https://github.com/seal-io/walrus-ui/commit/7e7c81aad24b7e9e0e8400bed962f2bc31a2ec67)
Result: PASS. The webservice template is rendered as expected. When Column is not set, the default colSpan is 6.

![Image](https://github.com/seal-io/walrus/assets/85595852/e731610c-13f0-4739-bd1a-59a5b7e46e55)



![Image](https://github.com/seal-io/walrus/assets/85595852/6f7ae732-b17e-4128-878d-be548c259eda)

**Comment by gitlawr** [comment]
@alexcodelf Why ports & envs are 100% width? We don't specify any span in https://github.com/walrus-catalog/webservice/blob/v0.0.5/schema.yaml

**Comment by alexcodelf** [comment]
> @alexcodelf Why ports & envs are 100% width? We don't specify any span in https://github.com/walrus-catalog/webservice/blob/v0.0.5/schema.yaml

The generated UI schema span is 12.
<img width="2343" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/cd49b7e6-6171-4d76-9015-01f396a82931">
<img width="2944" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/a6ff0efe-9003-4343-b7e9-a34ab930433b">
