### ISSUE TITLE
Edit in service list does not work

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1512]
https://github.com/seal-io/walrus/assets/5697937/e8095689-883b-4755-b429-4a9cc3d8dc3b

**Environment**
UI: dev-9a14b70
Server: dev-0a0e2f1

**Comment by gitlawr** [comment]
Verified in main

**Comment by gitlawr** [comment]
In UI version dev-de56cd1,
The edit action may be disabled for ready services.

Steps:
1. Create a service
2. Wait in the service list page until it's ready. Do not refresh.
3. Check the edit action of the service.


https://github.com/seal-io/walrus/assets/5697937/1a17ab92-32ac-4d14-b549-0c3dcbe11bab

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d
- UI version: dev-4874eff

**Test Result:**
Cannot edit service/resource on detail page too.
<img width="1560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/be82e00f-8c6c-455f-8e6b-80a6ba7f1e56">

**Comment by gitlawr** [comment]
Verify result: **Failed**

Edit in service detail page does not work.

**Comment by alexcodelf** [comment]
Verify result: PASS

Env:  UIdev-7e7c81a


https://github.com/seal-io/walrus/assets/85595852/1d588efd-bdb9-40e5-9b6a-ccc00d14b336
