### ISSUE TITLE
Showing discard change prompt on save

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1513]
**Steps to reproduce**
1. Edit a service of webservice type
2. Change the image
3. Keep the focus on the edited field.
4. Click Save

**Result**
A prompt telling user to discard changes pops up.

https://github.com/seal-io/walrus/assets/5697937/d6941863-60e2-43af-a253-eb2f7f070874

**Environment**
- Walrus version: main

**Comment by gitlawr** [comment]
Verify result: **Failed**

In UI version dev-9cbb6ba

The prompt still pops up on save
<img width="1427" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/6111ea34-cc73-4e5c-8263-afc488c8b427">

**Comment by gitlawr** [comment]
Issue 2:
Edit a service, change nothing and click cancel. The prompt also shows up.

**Comment by gitlawr** [comment]
Happens again in main

**Comment by gitlawr** [comment]
Verified in UI dev-ed9e02d

**Comment by gitlawr** [comment]
Still happens by the following steps:
1. Add a resource definition with kubernetes-redis and static-redis templates
2. Create a resource from the definition

**Comment by gitlawr** [comment]
Another way to reproduce:
1. Create a service using `static-postgresql` template.

**Comment by shanewxy** [comment]
Verified in main.
