### ISSUE TITLE
Cannot edit services in the stopped state

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1514]
**Describe the bug**

**Steps to reproduce**
1. Create a service and stop it.
2. Edit the service.

**Result**

1. Do not allow clicking the "Edit" button.
<img width="1213" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/524f1a69-ccb0-4f8b-b79c-b1982d9eaa8a">

2. Check the service status, `transitioning` is true.
<img width="553" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5fbcc5d0-f695-43dd-b16a-e218e9c4177f">

**Expected behavior**

Service in stopped state is editable.

**Environment**

- Walrus version: 52c962b9582a964d48188aa390f7ca7e490f0115
- UI version: dev-de56cd1

**Additional context**

**Comment by gitlawr** [comment]
transitioning stopped is an API issue fixed in b78506fb058d1904c218437dde2cce0db810a8ff.
UI should not depend on the transitioning state to disable editting though. In some cases like `Preparing`, the component status is not available but the service should be editable.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1

**Test Result:** pass

Resources that are in Stopped and Preparing states can be edited.
