### ISSUE TITLE
Fail to import schema with variable type list(map(any))

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1519]
**Describe the bug**

<img width="1828" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/1f2ecdaf-57d6-4efe-883c-1b69189cf0bf">

**Steps to reproduce**

Add a template with source https://github.com/unitong/test-variable

**Result**

Version v0.0.7 with `list(map(any))` variable fails to validate

**Expected behavior**

Import the template version successfully

**Environment**
- Walrus version: d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d

**Additional context**

**Comment by gitlawr** [comment]
Is it the same as https://github.com/seal-io/walrus/issues/1509?

**Comment by shanewxy** [comment]
> Is it the same as #1509?

Seems not the same. In this problem, templates with `list(map(any))` cannot be imported in the beginning. In #1509, the variable type is `list(map(string))` which can be imported

**Comment by shanewxy** [comment]
**Environment**: abc217a55cf7a6c0c39d4f8dec61d32ced2436b7
**Test result**: Pass
