### ISSUE TITLE
Sometimes need to click the save button twice to create a service

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1527]
UI version: dev-7e7c81a

https://github.com/seal-io/walrus/assets/5697937/b6add085-b9e5-4476-943a-5783580ecf32

**Comment by alexcodelf** [comment]
Env: UI dev-1421030
Test Result: Failed
  Still need click twice to create

https://github.com/seal-io/walrus/assets/85595852/4cd424c0-372a-4649-a227-6d6cbe775dc1
