### ISSUE TITLE
Be able to remove context variable in schema

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1528]

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 9735afb411c8b8bef83e11d048bb6a93494ac3ff
- UI version: dev-f0b97d5

**Test Result:**
- UI
1. Add a template with source `https://github.com/unitong/test-variable?ref=main`.
2. Go to the template details page and check the UI schema.

Still shows `context`.
<img width="1252" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e4593f11-3a6c-42cb-b13c-249bb2ae1eba">

- CLI: block by https://github.com/seal-io/walrus/issues/1788

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 7428401fef1d1a45e433c2e7722597a5e12830ef
- UI version: dev-6762e0b

**Test Result:**
Import a template without schema.yaml will still generate context variable for UI schema.

https://github.com/Finenyaco/terraform-kubernetes-containerservice?ref=main

<img width="1419" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f430389f-6eea-4315-a6ff-97dfc23933b2">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Test Result:** pass
