### ISSUE TITLE
[CLI] cannot run a workflow

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1535]
1. subcommand should be `run` instead of `run-request`
<img width="609" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/9f8a0113-28e4-430e-b39c-88baa720816c">

2.  run gets error
<img width="812" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/70b6dadb-b14b-4aa5-ba54-4cf1f2a8febc">

**Comment by alexcodelf** [comment]
Env: walrus-server: abc217a55cf7a6c0c39d4f8dec61d32ced2436b7
Test Result:  PASS

Now cli can run a workflow.


https://github.com/seal-io/walrus/assets/85595852/69ad822e-062f-4c79-994a-1d6f118daf07
