### ISSUE TITLE
Containerservice template not mounting file

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1538]
**Describe the bug**

**Steps to reproduce**
1. Create a service using containerservice template.
2. Fill in the `Files` field.
<img width="694" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/13619ed8-dc30-4d11-b4ff-b7293228cc08">

3. Check the pod created in k8s.

**Result**

No volume created.
<img width="619" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/ca8f7efd-a27e-48fc-88b8-cd6ae53ee095">

**Expected behavior**

Volume mounts successfully

**Environment**
- Walrus version: main d96e8a0e7bf4e2a7c68285cb47b204f4aa0c714d
- UI version: dev-7e7c81a

**Additional context**

**Comment by thxCode** [comment]
@shanewxy can you have a try again? the latest container service cannot reproduce this issue on my side.

<img width="865" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/640693b6-675a-4f27-bf94-5c1e51819d32">

**Comment by shanewxy** [comment]
Verified in main
