### ISSUE TITLE
Better widget for container service command

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1545]
**Is your enhancement related to a problem? Please describe.**
1. Now the container command input widget is wired, need another widget to input command
<img width="1196" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/fb72251f-aa8c-42e6-a1d7-916a539bc484">

**Describe the solution you'd like**
Better command list widget, may like

<img width="705" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/d1643954-df44-45d6-8b6b-9d4d6d99741a">

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1

**Test Result:** 

<img width="1174" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ef09e413-bcf6-48f0-8b08-3751cb282c28">
