### ISSUE TITLE
Failed to delete template

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1547]
**Describe the bug**
Delete template return bad request

**Steps to reproduce**
1. Pick a template and delete it
2. It returns a bad request
3. Check the request, find an invalid request body

<img width="1642" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/23f4e2a9-2d3d-4ad0-907c-c11fb324d93b">

**Expected behavior**
Should input valid request body

**Environment**
- Walrus version:
https://github.com/seal-io/walrus/commit/abc217a55cf7a6c0c39d4f8dec61d32ced2436b7

**Additional context**

**Comment by gitlawr** [comment]
Verified in main
