### ISSUE TITLE
The display for long template name is ... 

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1550]
**Describe the bug**

**Steps to reproduce**
1. import an independent template with name "terraform-kubernetes-containerservice-main"
2. then check the template list

**Result**
1. Found the name is replaced with ...
2. Click other template could view the details, but ... can't be clicked, click the red box area, could view the ... template's details
<img width="1032" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/2d484ef1-8917-4f26-9bf9-32044cfffe97">

<img width="953" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/f129833b-e6d1-49b3-8c5e-79252ee1d5a8">

<img width="736" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/78d7239a-4412-44e7-a121-73e8c171539f">

**Expected behavior**

For long name, could display the prefix, and the name could be clicked to view the details like others

**Environment**
- Walrus version:
UI dev-2b3fc20
**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c7fc65ae3ea5546452dd515722f9f0c0712c3e15
- UI version: dev-f0b97d5

**Test Result:** Template table and enable for service button have been removed.
<img width="1579" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/775a3229-6edd-4d12-9eaa-b6a872c8bf0a">
