### ISSUE TITLE
cost management options display exception

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1557]
**Describe the bug**

- There are some finops-disabled cluster names listed under Cluster 
- There are no project names listed under Project.

**Steps to reproduce**
1. Configure two Kubernetes connectors, one of them need to enable FinOps.
2. Navigate to "Cost Management" page, and switch to "Cost Analysis" pane.
3. Select `Cluster` then click right-hand option list.
4. Select `Project` then click right-hand option list.

**Result**

the `test` cluster is not enabled FinOps, but we can list it from the option control.

<img width="519" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/d09b3546-6f24-4918-8f1d-f5faaaa3bd39">

the project option control has nothing.

<img width="511" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/9b50e20f-28a7-4ee2-ac33-44fd99336365">

**Expected behavior**

1. Selected time-picker at first, so we can know which clusters incurred costs during the picked time range.
2. Give a tip or description to tell the user that ingested data generate the option list.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by aiwantaozi** [comment]
How the dropdown shows the selection option of cluster/project which has cost data. Maybe the time picker should be the first condition user input could be better.

**Comment by gitlawr** [comment]
No more valid in the latest version
