### ISSUE TITLE
No auto-completion for workflow variable 

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1558]
**Describe the bug**

**Steps to reproduce**
1. Create variables in workflow
2. Use the variable

**Result**

No auto-completion. User need to input manually.

**Expected behavior**

Support auto-completion like service. 

**Environment**
- Walrus version: v0.4.0-rc3
- UI version: v0.4.0-rc3

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 278965251ef397a0f67ffab3c9348f4243d92c56
- UI version: dev-bb09fa3

**Test Result:**

The autocomplete prompt is `workflow.var-name`, but in reality, `workflow.var.var-name` is the effective syntax.

Should the backend be modified to use `workflow.var-name`, or should the frontend be modified to use `workflow.var.var-name`

<img width="527" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/85939eda-581d-42eb-8e59-7d90ddf12d40">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main f41cb2758ccafbd4e458c1b171345b1987aa3247
- UI version: dev-2c4d8f3
- 

<img width="495" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/235a08d3-5c4b-49b1-bbb2-240f0eadadcc">
<img width="498" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/001641d7-95cb-44b9-8f3a-2ad50c8dfde3">
