### ISSUE TITLE
Enhancement for resource access address

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#156]
**Version:** main
**UI:** dev-f2d9c29
**Commit ID:** 26d4168e55f94fa6fd9c53e5c83a1363ba9e773f
**Env:** MacOS 13.1, Apple M2

**Test Steps:**

1. Deploy an instance by `webservice` module v0.0.2
2. Access the resource.
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/26084756/226541361-2178ee7f-efe9-4018-a742-086a328d4879.png">

3. It is the intranet address, and seal cannot access this address.
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/26084756/226541687-9bcdd15a-26e4-4423-895e-845f69d7f04a.png">

4. Manually modify it to an address that can be accessed by seal. Same as address in kubeconfig file.
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/26084756/226541837-05498fc7-50b7-4b65-a79c-deadad091a85.png">

**Comment by thxCode** [comment]
Closed in favor of https://github.com/seal-io/walrus/pull/1861, a walrus resource's `endpoints` or `walrus_endpoints` outputs determine the endpoints.
