### ISSUE TITLE
Descrition of the matching rules for resource definition.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1563]
**Is your enhancement related to a problem? Please describe.**

Currently, on the resource definition detail page, there is no explanation for the matching rules, making it difficult for users to understand their purpose.
<img width="2868" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/f1fdf41a-233e-4517-bd5d-83ebeb6f7ab8">

**Describe the solution you'd like**

Add descrition of matching rules.

**Describe alternatives you've considered**

**Additional context**

**Comment by hibig** [comment]
There is a help link to the corresponding document, on the current page.

**Comment by alexcodelf** [comment]
Do we need to add some brief introductions of the functions for each module instead of having users refer to the documentation?

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:** 

The current hints are not clear enough. This enhancement requires further discussion.

<img width="2545" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/32de540c-78d7-4ffe-b00f-fa72f60e992b">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-8ceaed8

**Test Result:**

Please remove the prompts in the new template page and proceed with the optimizations discussed in the meeting.

<img width="2552" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8d194e5d-0ea9-457f-81ba-cbc7a824f366">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-659510e

**Test Result:** pass

<img width="1576" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a5a4364b-7e37-40fd-82f2-ef6c919a8488">
<img width="1563" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0d1714a4-7639-42d7-b134-c672a6325c06">
<img width="1589" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/02ea37ad-235a-41f7-8abd-d26329f6d1d9">
