### ISSUE TITLE
Can't  create a environment when the name length is 63.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1564]
**Describe the bug**

**Steps to reproduce**
1. Create a environment, enter a name with length is 63.
2. Save

**Result**

1. Response 500 error.

<img width="1530" alt="截屏2023-11-24 17 04 48" src="https://github.com/seal-io/walrus/assets/24664190/b1d7bb6d-ebd4-4651-9dc4-0dfb628c4ca2">

**Expected behavior**

1. Create a environment successfully.

**Environment**
- Walrus version: main

**Additional context**

**Comment by shanewxy** [comment]
The error is from Kubernetes namespace creation, including project name + environment name. Can we dynamically limit the environment name length on UI?

**Comment by thxCode** [comment]
@shanewxy , should we use https://developer.hashicorp.com/terraform/language/functions/substr to avoid this?

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:** 

Project, environment, and resource names are limited to 30 characters in length.

- API: pass
- UI: pass
