### ISSUE TITLE
cannot see the UI Schema reversion confirm box under Full Screen mode

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1565]
**Describe the bug**

Cannot see the UI Schema reversion confirm box under `Full Screen` mode.

**Steps to reproduce**
1. Go into any template's detail page.
2. Select `UI schema` pane,  click `Full Screen` mode.
3. Click `Edit`, and modify some rows.
4. Click `Reset to default`. 

**Result**

Nothing changed, but saw the confirm box after out of `Full Screen` mode.

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/10cd0faa-4620-4228-a18d-3d3e10b740c8">

<img width="2498" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/f9a1a27d-8ed0-4a3f-9934-7b5ffad88520">

Confused about the relationship between the following buttons.

- `Cancel` is for exiting the editing mode.
- `Save` is for storing the modification, but the `Cancel` can also truncate the change.

<img width="464" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/f3854c01-0bf6-4c2d-8829-bcdb742eff8c">

**Expected behavior**

- Give up the `Full Screen` mode, and use the frozen header when scrolling down a long page.
- Keep the pane always in editing mode, then provide `Save`, `Reset to default` directly on the top bar.
    + Without saving, the change content will never be in. // do not need a cancel button.
    + `Reset to default` only reloads the default schema on the editing pane, then use `Save` to keep the change.
    + Maybe we can offer more operations, like Undo, and Redo.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e462fc8e68c52778f70f5b56c9eb0401a9a88fcf
- UI version: dev-aae40b4

**Test Result:**

Still retains full-screen mode, but not fully utilizing the large screen.

<img width="865" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4bf7d6d8-60eb-4ae7-89ca-4594592f335f">


<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e9109fdd-0f14-43b6-bbe4-d5356f8088e8">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c7fc65ae3ea5546452dd515722f9f0c0712c3e15
- UI version: dev-61f3704

**Test Result:** 

- Give up the Full Screen mode. 
- Remove the Edit button on the top bar, but still keep the reset button hidden.
- Keep the edit button, because some users do not have editing permissions.
- Support undo.

<img width="2445" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/82ec8743-8525-4805-9d88-7e4549af2089">
