### ISSUE TITLE
Can not clone resource to new env as draft.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1566]
**Describe the bug**

**Steps to reproduce**
1. create resource definition
    <img width="1724" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/c22820ea-43e9-4160-aae5-4c403dd7b209">
2. create a resource and service in env.
3. clone resource and service to new env as draft.

https://github.com/seal-io/walrus/assets/85595852/f5b3c4f6-6d0f-457e-a156-a36ecbffd521

**Result**

Can not clone and save as draft to new env.

**Expected behavior**

Can clone and save as draft to new env.

**Environment**
- Walrus version:  v0.4.0-rc3

**Additional context**
<img width="1195" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/a601ce49-edae-4570-968b-78c14941bb39">
<img width="1163" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/89a0acc7-1194-4bd4-b799-1d0503e11cd8">

**Comment by shanewxy** [comment]
Verified in main.

![Image](https://github.com/seal-io/walrus/assets/45061862/54f1f97c-67cd-406c-877f-7404910a274e)
