### ISSUE TITLE
Workflow steps sometimes not showing environment name

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1569]
**Describe the bug**

**Steps to reproduce**
1. Create a workflow.
2. Create two steps.
3. Run the workflow and go to the execution detail page.

**Result**

The first step shows no environment. Checking the response, environment name is an empty string.

<img width="942" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/a79fa8f7-ff30-4cc2-a57b-81bf7a4f6811">

**Expected behavior**

Step can show correct environment name.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by Finenyaco** [comment]
May be related to https://github.com/seal-io/walrus/issues/1388

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1

**Test Result:** Cannot be reproduced in v0.5.1
