### ISSUE TITLE
[v0.4.0-rc3]Resource Label value not shown.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1570]
**Describe the bug**

<img width="3006" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/463462ed-03ef-486d-86da-e7e5fe52fd01">
When edit a resource have label `walrus.seal.io/stoppable` : `false`,  the label value is missing.

**Steps to reproduce**
1. Create a service and add a label `walrus.seal.io/stoppable` : `false`.
2. Deploy the service.
3. Edit when the service finished deployment.

**Result**

false value of label  `walrus.seal.io/stoppable`  is missing.

**Expected behavior**

Show the value `false`

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by gitlawr** [comment]
Verified in main
