### ISSUE TITLE
[v0.4.0-rc3] Stop resource save draft status error

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1573]
**Describe the bug**

When update a stopped resource and save as draft. It status is still `stop`.

**Steps to reproduce**
1. Edit a stopped resource.
2. Save as draft

Uploading 录屏2023-11-24 17.54.24.mov…

**Result**

Resource status is stop.

**Expected behavior**

Resource status change to `undeployed`.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by gitlawr** [comment]
Why do we expect the status change to `undeployed`? It seems reasonable to be in `stopped`.

**Comment by alexcodelf** [comment]
Stop seems more reasonable than undeployed in this senario.
