### ISSUE TITLE
[v0.4.0-rc3] use available source example on template adding page

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1574]
**Is your enhancement related to a problem? Please describe.**

The source example of template adding is unavailable.

<img width="626" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/4c49656b-0e39-485f-a216-667e629bb962">

**Describe the solution you'd like**

Provide an available case, like https://github.com/terraform-aws-modules/terraform-aws-vpc

**Describe alternatives you've considered**

**Additional context**

**Comment by gitlawr** [comment]
<img width="537" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/84f82916-3aea-4583-8f67-ec044b602e45">

I think we need to explain the field, not showing one of the cases. Now `ref` looks like required. It would be better to show both cases in examples:

```
URL of a git repository. Use the ref query parameter if you want to use a specific version. For example:
https://github.com/terraform-aws-modules/terraform-aws-vpc
https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=main
```

**Comment by shanewxy** [comment]
Verified in main.

![Image](https://github.com/seal-io/walrus/assets/45061862/8207582f-3210-4f6d-aa89-4eb88e73d160)
