### ISSUE TITLE
[v0.4.0-rc3]Can not stop resource when dependant resources is stopped.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1575]
**Describe the bug**

Can not stop resources event  though dependant resources is stopped.

**Steps to reproduce**
1. Create services A and B. Make B depend on A.
2. Stop service B
3. Stop service A when B is stopped.

https://github.com/seal-io/walrus/assets/85595852/0ace643f-b2f7-453b-b42a-8b26a95b10a8

**Result**

Can not stop A, show message: `resource about to be stopped is the dependency of: B`

**Expected behavior**

Can stop service A.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by shanewxy** [comment]
Verified in main.

![Image](https://github.com/seal-io/walrus/assets/45061862/b9f153ed-c7a9-40cb-b8ae-06674ecd53e1)
