### ISSUE TITLE
Workflow status not updated when execution failed

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1576]
**Describe the bug**

**Steps to reproduce**
1. Create a workflow.
2. Create approve and service steps.
3. Reject the approval step.

**Result**

Execution failed but the workflow status was still running. The status updated after refreshing. 
<img width="365" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/f6451810-b1a9-4d52-b505-0d7bacc6ea73">
<img width="559" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/d51f3623-0ee0-4205-a53c-a78431f07b01">

**Expected behavior**

The workflow status updates automatically.

**Environment**
- Walrus version: v0.4.0-rc3
- UI version: v0.4.0-rc3

**Additional context**

**Comment by alexcodelf** [comment]
Can not repreduce in main.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:**

After a step failure, there is a need to wait for a while for the workflow to refresh by design.
