### ISSUE TITLE
[v0.4.0-rc3]Can not stop resource type resources.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1578]
**Describe the bug**

Stop env can not stop resource.

https://github.com/seal-io/walrus/assets/85595852/97fbcbbd-ac67-471f-9e45-8de36946715d

**Steps to reproduce**
1. Create a resource in env, and deployed to succeeed.
2. Stop resource.

**Result**

Failed to stop resource.

**Expected behavior**

Could Stop resource.

**Environment**
- Walrus version: v0.4.0-rc3

**Additional context**

**Comment by gitlawr** [comment]
This is by design. By default services are stoppable and resources are not. You can set `walrus.seal.io/stoppable` label to change the default behavior.

**Comment by alexcodelf** [comment]
close as not a bug
