### ISSUE TITLE
[v0.4.0-rc3] failed to use repo subpath importing template

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1579]
**Describe the bug**

Failed to use a template imported by repo subpath to create a service.

**Steps to reproduce**
1. Prepare an Environment connected with a Kubernetes connector.
2. Import a template from a repo's subpath, like: https://github.com/thxCode/walrus-testing-template//modules/aws-vpc?ref=main
3. Create a service with the template created by step 2.

**Result**

Failed to use the real module under the subpath.

<img width="697" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/42f31e10-1e30-4e71-aa97-a2e2e1dd5432">

<img width="1325" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/63ddc30d-b0d8-4975-934f-66ad84b4b1a2">

<img width="653" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/18d97d1b-153a-49d0-8991-57084054c46f">

**Expected behavior**

Work with the template imported by subpath.

**Environment**
- Walrus version:

**Additional context**
None

**Comment by shanewxy** [comment]
Verified in main.


![Image](https://github.com/seal-io/walrus/assets/45061862/168f212c-c0f4-4f45-97af-bd655fcde7dc)

![Image](https://github.com/seal-io/walrus/assets/45061862/7e8c672d-adfc-4ed1-b5cd-99282258d929)
