### ISSUE TITLE
Could not clone the resource: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1585]
**Describe the bug**
Could not clone the resource:
panic observing: runtime error: invalid memory address or nil pointer dereference.

**Steps to reproduce**
1. Add a template: https://github.com/walrus-demo-catalog/kubernetes-namespace;
2. Add a ResourceDefinition using the kubernetes-namespace template;
3. Create a resource using namespace ResourceDefinition;
4. Clone the resouce to another environment.

**Result**
<img width="896" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/6118e087-b967-4433-88bc-6060d6bc453f">
<img width="1019" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/4c347d61-4133-483c-90ab-c9e21fca3c2a">
<img width="589" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/89a88318-8acb-46fc-aeec-238071642e70">

**Environment**
- Walrus version: v0.4.0-rc3

**Comment by gitlawr** [comment]
Duplicate to https://github.com/seal-io/walrus/issues/1566
