### ISSUE TITLE
The resource cannot be saved while editing

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1587]
**Describe the bug**
The resource cannot be saved while editing.

**Steps to reproduce**
1. Add a ResourceDefinition using the rds template;
2. Create a resource using rds ResourceDefinition;
3. Edit the resource.

**Result**
The resource cannot be saved while editing.

**Environment**
- Walrus version: v0.4.0-rc3

**Comment by aiwantaozi** [comment]
Verified in UI dev-bbbc8da
Could update resource create by resource definition
