### ISSUE TITLE
Resource component status color wrong

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1591]
**Describe the bug**

Stopped aurora1-cluster-demo is stopped， color is green。
<img width="1674" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/cbf9ad98-2a11-4f95-b66a-83603c48eeaa">

**Steps to reproduce**
1. import template `https://github.com/Finenyaco/modules_test//aws/aws-rds-cluster/0.0.2?ref=main`
2. create resource with aws connector
3. wait deployed and manually stop cluster in aws.
<img width="1366" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/efea3081-f56c-46b4-bd14-5a8994f03828">

**Result**

After status synced. Status turns to stopped but color is green.

**Expected behavior**

just like resource stopped, it is gray or red.

**Environment**
- Walrus version: v0.4.0-rc2 (after subpath fixed or modify template version source to test it)

**Additional context**

<img width="759" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/06f886b1-896d-484b-ab29-3e11fd5e75dd">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c7fc65ae3ea5546452dd515722f9f0c0712c3e15
- UI version: dev-f0b97d5

**Test Result:** pass

<img width="2283" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/aef13fc5-ac36-432a-9a9f-2058547eac44">
<img width="2394" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e6cde198-dbfe-41ee-974d-8bb28e6ee383">
