### ISSUE TITLE
The resource definition variable description is confusing

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1593]
**Describe the bug**

**Steps to reproduce**
1. add resource definition matching rule 1 with: terraform-alicloud-rds-mysql
2.  add resource definition matching rule 2 with: terraform-aws-rds-mysql
3. double-check the input description, could find the alicloud link, it is comfused while use aws
<img width="1824" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/74ecaccf-6661-41f9-9574-295b6864422b">

<img width="1867" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/9da8b59f-a7d5-44ef-8038-2b2a476c94c1">

<img width="1882" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/5b575ee0-3d06-4072-b9cd-461609695291">
4. create an environment with aws connector
5. then create a resource with the definition created just now, could still find the alicoud link in description
<img width="1870" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/66ceb819-6107-4cb6-b0bb-4f37f5ba63f8">

**Result**

**Expected behavior**

**Environment**
- Walrus version:

**Additional context**

**Comment by gitlawr** [comment]
Now, the generated definition schema is based on the expectation that common variables in each template are homogenous. If the description is provider specific, we are not able to generate a general description. However, users who manage resource definitions can customize it by modifying the UI schema.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1

**Test Result:** 

Related to https://github.com/seal-io/walrus/pull/1652.

- When there are **no** completely identical and **full** sentences in the description:
<img width="2437" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/569c476e-1439-496d-b151-bf750edc1751">

- When there are completely identical and full sentences in the description:
<img width="2466" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5ed74567-cb12-4c0b-8264-0807cef74437">
