### ISSUE TITLE
While the user doesn't input the attribute, the attribute in the resource definition doesn't work

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1595]
**Describe the bug**

**Steps to reproduce**
1. create resource definition with a template terraform-static-mysql and empty selector

2. input Hosts Readonly field with 192.168.0.1:8080
<img width="1088" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/ebaca993-dd9a-4fcb-850b-0f72d5a92455">

3. deploy resource with that resource definition, leave the field Hosts Readonly empty
<img width="1187" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/a5e1f771-5259-41a8-af5c-199760bd85f6">

4. the output endpoints_readonly is also empty
<img width="1424" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/8fcc428a-7ff4-4839-81f2-11e730ac5cfd">

**Result**
The resource definition's attribute does not work.

**Expected behavior**
While the user doesn't input the attribute, should use the attribute in the resource definition

**Environment**
- Walrus version:
v0.4.0-rc3

**Additional context**

**Comment by gitlawr** [comment]
How do we differentiate user doesn't input or user want empty input for the attribute? If resource definition manager want a default value, we should guide him/her to set the default in definition schema.

**Comment by aiwantaozi** [comment]
While removing the attribute from the resource definition UI schema, the default value from the resource definition worked.
The design is while the attribute allows the user to configure, only use the attribute user input. While the attribute isn't allow user to configure, use the attribute value int the resource definition.
