### ISSUE TITLE
be able to refresh template schema of a force-pushed tag

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1597]
**Is your enhancement related to a problem? Please describe.**

Some scenarios want to avoid version upgradation but be able to refresh its schema. Although we do not update the schema of an existing tag, the new change in the template is still available, which results in inconsistency between what is seen and what is deployed.

**Describe the solution you'd like**

Be able to refresh template schema, no matter from the refreshing of one template or batch refreshing from the catalog.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ce9f6f458d0e8facdc2448ccfe78b0ee434b301b
- UI version: dev-e0bc105

**Test Result:** pass
