### ISSUE TITLE
description in output reference is not readable

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1598]
**Describe the bug**
<img width="813" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/ebef4ffa-6d55-47fb-ae7d-1bb51e844538">

**Steps to reproduce**
1. Create a kubernetes-mysql
2. Create a webservice and use the mysql output

**Environment**
- Walrus version: main

**Comment by gitlawr** [comment]
Issue 2: Missing some outputs in the list, but you can search it. For example, the username of mysql output:

https://github.com/seal-io/walrus/assets/5697937/b21468e5-2508-4f24-af92-d39914cb1243

**Comment by shanewxy** [comment]
Verified in main.

<img width="244" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/bdbcfe8a-559a-4d64-98d7-34d775c02ae6">
