### ISSUE TITLE
[CLI]walrus config current-context returns empty

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1607]
`walrus config current-context` returns empty:
<img width="257" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/ab41f34a-09de-475a-927f-6e8e8a16caa0">

**Comment by Finenyaco** [comment]
Cannot reproduce in v0.4.0

```
 ~/.walrus/ walrus -v
walrus version v0.4.0 (501535b858f4bbfb681ab45af9ca332b96c776aa)
 ~/.walrus/ walrus config current-context
Current Project: default
Current Environment: orb-dev
```

**Comment by linyinli** [comment]
Probably because there is no project and environment set up when running `walrus config setup`, should it be displayed as:
Current Project:
Current Environment:

**Comment by linyinli** [comment]
<img width="333" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/c083b374-dee0-4597-b1d5-ddf819ebecfa">

Great!
