### ISSUE TITLE
Cannot stop the environment: subject id is empty

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1609]
**Describe the bug**
Cannot stop the environment: subject id is empty.

**Steps to reproduce**
1. Create three services: db, backend and frontend. The backend depends on the db, and the frontend depends on the backend;
2. Stop the environment.

**Result**
<img width="1265" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/203b9533-c653-481e-8bff-cbbbfc15b759">

<img width="835" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/a1f3ef0e-50db-4722-bab8-58511133983c">

**Environment**
- Walrus version: v0.4.0-rc3

**Comment by gitlawr** [comment]
Probably related to https://github.com/seal-io/walrus/issues/1470

**Comment by shanewxy** [comment]
Cannot reproduce in main
