### ISSUE TITLE
View logs from the app container by default, not the init container

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1611]
View logs from the app container by default, not the init container:
<img width="1504" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/28ff4fce-db09-4bca-ad80-7a0bd2e388fe">

**Comment by hibig** [comment]
The data returned in the API  ```projects/{projectID}/environments/{environmentID}/resources/{resourceID}/components```  requires the value of ```resource.name```.



![Image](https://github.com/seal-io/walrus/assets/24664190/a583eebe-f7f1-4f9d-9ff0-6f23472a1431)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 1a7081b174c9781533116ce301abd5bc46d4043a
- UI version: dev-71a5388

**Test Result:** pass


<img width="485" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5e011e9b-32f0-424d-bc64-a3961d2f6dab">
