### ISSUE TITLE
Cannot start the environment when services are cloned from other environment and has dependency links

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1612]
**Describe the bug**
Cannot start the environment when services are cloned from other environment and has dependency links.

**Steps to reproduce**
1. Create three services: db, backend and frontend. The backend depends on the db, and the frontend depends on the backend;
2. Clone those services to another environment as draft;
3. Start the another environment.

**Result**
failed to apply resource: resource backend dependency output db_db_host not found:
<img width="1270" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/918c0f88-735a-4c2b-b162-64357cf00b69">

**Environment**
- Walrus version: v0.4.0-rc3

**Comment by shanewxy** [comment]
Verified in main.
