### ISSUE TITLE
Edit service UI issue

### ISSUE THREAD

**Issue by shanewxy** [seal-io/walrus#1620]
**Describe the bug**

**Steps to reproduce**
1. Create a service using `https://github.com/unitong/test-variable` version 0.0.7.
2. Edit and change to version 0.0.8.

**Result**

<img width="724" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/2ad09e1f-e23a-40c8-9282-eecb9b85c9f2">

<img width="475" alt="image" src="https://github.com/seal-io/walrus/assets/45061862/f70c45b0-75ed-4234-a37a-6a581210e95d">

**Expected behavior**

Display properly.

**Environment**
- UI version: dev-e6fb7f8

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8fc1ee8f23f152bbeaf1aec685c03d15ffbccae1
- UI version: dev-199faf2

**Test Result:** No empty option after switching the version. But it does not show the default values https://github.com/seal-io/walrus/issues/1656.

<img width="767" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4f11a83d-3d1d-4abd-bc59-d5d3e2f73f1b">
