### ISSUE TITLE
The default values of the template cannot be displayed when adding a new match rule in the existing resource definition

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1626]
**Describe the bug**
The default values of the template cannot be displayed when adding a new match rule in the existing resource definition.

**Steps to reproduce**
1. Add a resource definition;
2. Edit the resource definition, add a new match rule.

**Result**
<img width="1866" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/1436b44d-8d5e-4928-937f-770813347b19">

**Environment**
- Walrus version: v0.4.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 6d6811539cfc22ea3ae13429ab572c63a7908f0f
- UI version: dev-199faf2

**Test Result:** pass
<img width="2467" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1beb162b-6445-4023-95d4-3d8c5d52a2b2">
