### ISSUE TITLE
Create service returns error "invalid variables: invalid containers: Value is not nullable"

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1627]
**Steps to reproduce**
1. Create a containerservice
2. Input nginx image
3. Expand Ports
4. Click `+` to add a port.
5. Click `-` to remove the port.
6. Click the panel besides the `+` button (as is shown below)
7. Click `Save and Deploy`

<img width="715" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/dec8dd37-68f9-4f04-b2ff-1dc688551ec4">

**Result**

<img width="1435" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/c0467f4d-53a4-4667-8b1e-3cfbbf2a5cfc">

**Environment**
- Walrus version: v0.4.0

**Other Info**
If you collapse the Ports configuration it succeeds.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e462fc8e68c52778f70f5b56c9eb0401a9a88fcf
- UI version: dev-aae40b4

**Test Result:** Failed

<img width="2535" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/948069ee-815e-4e28-ae3a-4ebee3d4a4f0">

<img width="899" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a50d3120-8ff6-4839-9acc-6605b5a9b1f5">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-2fca30f

**Test Result:** pass
