### ISSUE TITLE
Two services with dependencies are stuck.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1628]
**Describe the bug**

**Steps to reproduce**
1. Create two services: service-a, service-b.
2. "service-b" depends on  "service-a".
3. Deploy them, then stop "service-b".
4. Back to environment list, toggle between the stop and start buttons multiple times, "service-a" and "service-b" status would be stuck.
<img width="1180" alt="截屏2023-11-26 20 04 31" src="https://github.com/seal-io/walrus/assets/24664190/2d69a0a7-6f01-4a89-88d9-d0edbebcc4b4">
<img width="1130" alt="截屏2023-11-26 20 04 51" src="https://github.com/seal-io/walrus/assets/24664190/c51637f9-4fa2-4444-80ab-bb21e3097dd0">

**Result**

**Expected behavior**

"service-a" and "service-b" status are normal.
**Environment**
- Walrus version: v0.4.0

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Test Result:**

It will turn to progressing failed status now. And need to redeploy it.

<img width="1566" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f631f00d-e60b-4aff-bcd0-d0fbc6c45cad">
