### ISSUE TITLE
Topic does not take effect when adding a standalone template

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1633]
**Describe the bug**

Topic does not take effect when adding an independent templates

**Steps to reproduce**
1. Add a template with source `https://github.com/walrus-catalog/terraform-kubernetes-containerservice`.
<img width="1407" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a1a9d749-a5fa-494e-b142-b826237dc51e">

2. Check the template.

**Result**

1. It is disable for services
<img width="633" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3a2c24e9-71bc-44bd-9e4a-28769b9c680e">

**Expected behavior**

1. If the topic of the template contains `walrus-service`, the template should be marked as `Enable for Service` automatically on import.

**Environment**
- Walrus version: v0.4.0

**Additional context**

**Comment by gitlawr** [comment]
No more valid in current version
