### ISSUE TITLE
The cloning service is sometimes deployed twice

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1634]
**Describe the bug**

The cloning service is sometimes deployed twice.

**Steps to reproduce**
1. Create an environment and add two services.
2. Clone the environment and check the service revisions.

**Result**

1. Sometimes the service status does not update after deploying.
<img width="2559" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c85aa6f7-2e27-4b10-b1fd-4b93e957b923">

2. And trigger deployment again in the next iteration.
<img width="2557" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/231e6935-8578-4988-a24d-18199ffe328f">

**Expected behavior**

Deployed only once after cloning.

**Environment**
- Walrus version: v0.4.0

**Additional context**

**Comment by alexcodelf** [comment]
Can not reproduce

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 42f6b1e6cbcd105e9e99ea8badacace1a799c043
- UI version: dev-2fca30f

**Test Result:**

Unable to reproduce in the latest version. Close the issue and if it can be reproduced, reopen it.
