### ISSUE TITLE
Each time the service is updated, the access URL is displayed as the NodePort endpoint

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1641]
**Describe the bug**
Each time the service is updated, the access URL is displayed as the NodePort endpoint, and replace it with the contents of endpoints output after refreshing.

**Steps to reproduce**
1. Create a kubernetes-mysql service with NodePort service type;
2. Check the access URL;
3. Refreshing and check the access URL again.

**Result**
<img width="1685" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/c56e166e-c133-40cc-a9bc-a64b99d06923">
<img width="1688" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/3d46bc9f-67c5-4d87-9e50-6509cff16183">

**Expected behavior**
Both should be displayed.

**Environment**
- Walrus version: v0.4.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 2ef0df227f0580311686bc6ae2ab19a9548bee94
- UI version: dev-6e415a8

**Test Result:** pass

<img width="1616" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d81f4450-f92d-4a26-a302-749bd3ef9767">

```
service/port                        NodePort    10.96.65.128   <none>        80:30614/TCP,8080:31008/TCP   12m
```
