### ISSUE TITLE
Support line wrapping when there is no space available for word wrapping

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1642]
**Describe the solution you'd like**
Support line wrapping when there is no space available for word wrapping:
<img width="1915" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/4ac98d9a-c81a-4d97-bc6e-0f68f76d41b7">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e92cde6256262c9671c9d51475f0bee8669f6628
- UI version: dev-606a1a9

**Test Result:** Failed, and the position of the scrollbar seems a bit odd.

<img width="2558" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/89fa546b-56cf-4263-8b8d-4e55f8f7a27d">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e92cde6256262c9671c9d51475f0bee8669f6628
- UI version: dev-606a1a9

**Test Result:** pass

<img width="2555" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/645836e8-0c47-42b6-8d56-0317c3b5d337">

<img width="2545" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/19b30a22-8355-4eb2-a7bc-cf3d24c85ab7">
