### ISSUE TITLE
Enhance the description of the command and the args variables for containerservice and containertask template

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1643]
**Describe the solution you'd like**
Enhance the description of the command and the args variables for containerservice and containertask template, how should it be filled in:
<img width="1671" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/98b2e969-71c3-4147-90b6-4909baea7c62">

**Comment by thxCode** [comment]
i think this is reasonable, as the command of kube is something like docker entrypoint, and the kube pod args is something like docker cmd. 

<img width="731" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/26e63a8c-4a8f-47e9-86d8-f0d6523d36ae">

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#volume cc @linyinli

**Comment by linyinli** [comment]
I just think that the format of how to fill this attribute should be written in the description, informing the user what format should be followed to avoid some mistakes.
