### ISSUE TITLE
The connector fields are not aligned with the fields of the other input fields

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1648]
**Describe the bug**
The connector field are not aligned with the fields of the other input fields when creating a PR in the AI Draft Template.
**Result**
<img width="1687" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/88d6466e-ade0-4de9-ad82-24be083d0329">

**Environment**
- Walrus version: v0.4.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ee6f73576bbb364db67bd41edb1ba2b148a6710e
- UI version: dev-f5933d5

**Test Result:** pass

<img width="914" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/55e3d59c-3249-43a4-9a6b-fd7860fbf748">
<img width="814" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/934413f3-8526-4ab0-887e-b8ea5f2a6075">

select a connector.
<img width="856" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c7a5427d-691b-4ab3-a71d-ebd6119d6d83">
