### ISSUE TITLE
Indicates that a service or resource with the same name exists but has actually been removed

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1661]
**Describe the bug**
When deleting a service and immediately creating a new one with the same name, it indicates that a service or resource with the same name exists but has actually been removed.

**Steps to reproduce**
1. Create the nginx service;
2. Delete the nginx service and click to add new service immidiately;
3. Use the same service name as nginx.

**Result**
Indicates that a service or resource with the same name exists but has actually been removed: 
<img width="748" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/5871eeff-e67f-4fcc-9f23-208fd77a286f">
<img width="624" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/9383d0cb-d9bf-4175-9e3e-ff20476fe283">

**Environment**
- Walrus version: v0.4.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a12b753f2e823aa7a7456110215dceed4da46ba1
- UI version: dev-07fa8db

**Test Result:** pass
