### ISSUE TITLE
When the service is just deployed, see that the deployment details log is empty

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1664]
**Is your enhancement related to a problem? Please describe.**
When the service is just deployed, see that the deployment details log is empty:
<img width="704" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/24d0f657-27c7-412e-b8a1-880c87cc19ef">

**Describe the solution you'd like**
Smoother transition between viewing logs from deployer pod and from database.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 73e6ce88f4205e030d30ff4276e82d687c0ccdd0
- UI version: dev-a942812

**Test Result:** It can reproduce in the latest version.


https://github.com/seal-io/walrus/assets/26084756/2474c667-5f67-407e-bd1a-4e2fc5c00885

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 0b2678c0df661cd20cafbdb716a641717f158e7f
- UI version: v0.5.0-rc2

**Test Result:** pass
