### ISSUE TITLE
It is prompted to fill in the value even though it has already been filled in when creating service

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1665]
**Describe the bug**
It is prompted to fill in the value even though it has already been filled in when creating service.

**Steps to reproduce**
Use kubernetes-mysql template to create a service.

**Result**
<img width="1292" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/cfd7dc6e-117f-4a25-87c3-9f58b972e627">

**Environment**
- Walrus version:
UI: dev-f5933d5
Server: dev-ee6f735

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ee6f73576bbb364db67bd41edb1ba2b148a6710e
- UI version: dev-a894cf7

**Test Result:** pass
