### ISSUE TITLE
Support variable references when the variable type is an array

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1666]
**Is your enhancement related to a problem? Please describe.**
Now arrays cannot reference the output of other services/resources when creating services/resources.

**Describe the solution you'd like**
Support variable references when the variable type is an array.

<img width="1293" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/e61fc424-fc97-4a8c-a526-725f9d928a3f">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main fcec81df221b37754b6be6b5657bbbfab845fabf
- UI version: dev-33d2ecd

**Test Result:** pass
<img width="1033" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0e467e19-1beb-4f2f-b85f-0cf88a444ecf">
