### ISSUE TITLE
Duplicate resources are displayed after resource creation

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1677]
**Describe the bug**
Duplicate resources are displayed after resource creation.

**Steps to reproduce**
Create a resource and save as draft.

<img width="1251" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/0b91cfc9-2192-4722-b983-fafc4f254131">

**Environment**
- Walrus version: 
UI: dev-d69ebcc
Server: dev-ee6f735

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ab30b62917ad1ab35c43d37fb7a646efbd9a1572
- UI version: dev-2d14c4a

**Test Result:** pass
