### ISSUE TITLE
Support inherit the attributes of the old version when updating template of the service to a new version

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1681]
**Is your enhancement related to a problem? Please describe.**
when the template of the service is updated to a new version, the attributes of the old version are replaced.

**Describe the solution you'd like**
1. Support inherit the attributes of the old version when updating template of the service to a new version;
2. Consider the merging of attributes and the handling of attributes for differences.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 73e6ce88f4205e030d30ff4276e82d687c0ccdd0
- UI version: dev-860ae96

**Test Result:** pass

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-4dd2e5a

**Test Result:** 

When upgrading the template version of a resource definition, please make it able to inherit the attributes from the original template too.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-8ceaed8

**Test Result:** pass
