### ISSUE TITLE
UI cannot operating while create resource definitions in UI

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1699]
**Describe the bug**
Can't create resource definition

**Steps to reproduce**
1. Go to the resource definition page
2. Click create resource definition
3. Then UI hangs, and can't cancel or save
4. Also the template version displayed in a messy way

<img width="867" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/94af2403-7efa-4312-be74-9b9568f81602">

**Result**
UI cannot operate while creating resource definitions in UI.

**Expected behavior**

**Environment**
- Walrus version:
UI version [e880ee](https://github.com/seal-io/walrus-ui/commit/e880ee914068cc08fe762e9fbad8a4fb5e418368)
server version 387b458b939852736bdcc40f2f83fec184da6b3f

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 387b458b939852736bdcc40f2f83fec184da6b3f
- UI version: dev-4478a77

**Test Result:** pass**Environment**
- Walrus version: main 387b458b939852736bdcc40f2f83fec184da6b3f
- UI version: dev-4478a77

**Test Result:** pass
