### ISSUE TITLE
After saving the draft and deploying the service, some configurations were lost

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1727]
**Describe the bug**

After saving the draft and deploying the service, some configurations were lost

**Steps to reproduce**
1. New a service using `kubernetes-containerservice` template.

2. Add a port and save as draft.

<img width="1103" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e2af1579-fe5c-450c-80f3-f0e176922157">

3. Start the service.
4. Go to the service details page and check the template configuration.

**Result**

1. The external port is empty.
<img width="2488" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/01cdc2ca-7d96-4e6d-b756-bdb921af4285">

**Expected behavior**

**Environment**
- Walrus version: main 0bde30233f43610dfcdcdaa3d925982fb461f07b
- UI version: dev-784f2b6

**Additional context**

**Comment by shanewxy** [comment]
Cannot reproduce in main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 73e6ce88f4205e030d30ff4276e82d687c0ccdd0
- UI version: dev-c4e1639

**Test Result:**  Cannot reproduce in the latest version
