### ISSUE TITLE
 Issues with the user center permissions list

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1730]
**Describe the bug**

**Steps to reproduce**
1. Create a general user and add them as a default project member.
2. Login walrus as general user.
3. Go to user center to check the user information.

**Result**

**Issue 1:**  The project permissions for "Service resources" need to be updated to "Service components."
<img width="2510" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8aa86beb-0d39-4bfe-bcce-2e0d358ce33f">

Issue 2: 
The content under "Application Management" in system permissions actually corresponds to the content under project permissions.
<img width="2502" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/db263d06-0bf8-4f44-8436-a6108bf44fed">

**Environment**
- Walrus version: main 0bde30233f43610dfcdcdaa3d925982fb461f07b
- UI version: dev-784f2b6

**Additional context**

**Comment by hibig** [comment]
The "/account/info" api should not return workflow-related resources, otherwise there will be workflow-related information in the system permission list. 

<img width="896" alt="截屏2023-12-13 18 44 29" src="https://github.com/seal-io/walrus/assets/24664190/06ac9d17-6bab-4252-8a68-9f4110521ea6">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main f287a04a0e0e04715f6b161ba77407d0e03d563e
- UI version: dev-b6cc5ea

**Test Result:** pass
