### ISSUE TITLE
Support catalog from Gitee and provide built-in catalog mirror in Gitee

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1736]
**Is your enhancement related to a problem? Please describe.**
It helps when it's inconvenient to access github for the built-in templates

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a34a2926d722730c5cbecda30238b778ba0329f0
- UI version: dev-98d0e3e

**Test Result:** 
setup walrus with `--builtin-catalog-provider=gitee`.

1. Check built-in catalog source.
<img width="806" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7377cfb3-7524-4d93-ad59-1201375aacd9">

2. Check deployment logs.
<img width="915" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/67d75dcc-32f1-4dde-b7c0-9cf1032428b4">

3. But cannot get the template icon.
<img width="2437" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7598be19-c04a-4ca6-9b81-7249be0e57ad">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 278965251ef397a0f67ffab3c9348f4243d92c56
- UI version: dev-bb09fa3

**Test Result:** pass

<img width="2422" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/41035ed7-519d-49dd-9b4a-fc0953550482">
