### ISSUE TITLE
Remove internal access endpoints

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1738]
**Is your enhancement related to a problem? Please describe.**
When a containerservice is deployed the following access endpoints are shown, but the in-cluster endpoint is usually inaccessible.
<img width="1091" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/5af3dc8e-b05a-4c2d-903c-528fb5ca215e">

**Describe the solution you'd like**
Remove internal access endpoints

**Comment by thxCode** [comment]
@Finenyaco the templates that tagged by v0.2.0, below walrus-catalog, have removed the endpoints output.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a34a2926d722730c5cbecda30238b778ba0329f0
- UI version: dev-98d0e3e

**Test Result:** pass

<img width="2469" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e8b8d5b1-4205-4de0-8108-17aa2384753a">
