### ISSUE TITLE
Resource is not deployed imediately on clone/batch creation

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1740]
**Is your enhancement related to a problem? Please describe.**
When we clone resources or call batch creation via API, they are in progressing for some period before the deployment start.

**Describe the solution you'd like**
Imediately start the deployment if there's no pending dependencies.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8048eb2af52e636e42e656ee507d875cb83999d9
- UI version: dev-33d2ecd

**Test Result:** pass
