### ISSUE TITLE
Walrus Server URL Check 

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#1749]
version: v0.4.1
Step to reproduce:
1. In Walrus server, go to "system settings” - "server management"
2. Try to update server address, the URL check behavior is weird. 
- walrus.abc.local works but walrus.oac.local doesn't
- walrus.ab.com works but walrus.ab.local doesn't
...... 
Not sure the standards for the check.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c7fc65ae3ea5546452dd515722f9f0c0712c3e15
- UI version: dev-fcd557e

**Test Result:** pass
