### ISSUE TITLE
Issue with service type of kubernetes-containerservice template

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1753]
**Describe the bug**

**Steps to reproduce**
1. Create a service using `kubernetes-containerservice` template without configuring an external port.
2. Go to the service details page and check the template configuration.
3. Check deployed resources on the Kubernetes cluster.

**Result**

1. The service type is `NodePort`. 
<img width="1238" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/37f2b9ee-17e4-4165-868b-2b55bee21778">

2.  The actual service type is `ClusterIP`. 
<img width="855" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/dc6fa3fc-3930-4047-8dcd-8eccf825dc87">

**Expected behavior**

**Environment**
- Walrus version: main fcec81df221b37754b6be6b5657bbbfab845fabf
- UI version: dev-33d2ecd

**Additional context**

**Comment by thxCode** [comment]
clarify the usage of this field in the description, https://github.com/walrus-catalog/terraform-kubernetes-containerservice/pull/16/commits/1d23e59c75c9b33f92061d9126dc543f0be2fb29.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Test Result:** kubernetes-containerservice v0.2.5 pass
<img width="1035" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/bf8aee1f-1abd-4fb0-a289-21568ed06ee0">
