### ISSUE TITLE
Return endpoints data in the resource list API.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#1755]
**Is your enhancement related to a problem? Please describe.**

1. In the resource list can view the item endpoints.

**Describe the solution you'd like**

1. Return endpoints data in the resource list API.

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-567aeb4

**Test Result:** Failed to display the endpoints when there are more than one endpoint.

<img width="2391" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1ab030ac-78d7-4ba8-9241-480d04e56b0a">
<img width="833" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5f52a773-768d-49a2-878d-3ff38b541e83">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-7590f46

**Test Result:** pass

<img width="1162" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8158a396-bd97-4942-aea1-60746068a9fe">
