### ISSUE TITLE
Add the walrus.seal.io/stoppable label to resource automatically after resource created

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1765]
Add the walrus.seal.io/stoppable label to resource automatically after resource created:

- For development/staging environments, `walrus.seal.io/stoppable=true` by default

- For production environments, `walrus.seal.io/stoppable=false` by default

**Comment by linyinli** [comment]
A few details need to be added: remove walrus.seal.io/stoppable label when cloning and make it fit to environment type.

**Comment by thxCode** [comment]
Following the description, @linyinli 's first requirement is to add stoppable to all resources, but the main branch only supports adding the stoppable label to the resources below the non-production env. Can @linyinli clarify what the real requirement?

**Comment by linyinli** [comment]
Real requirement:
1. walrus.seal.io/stoppable label need to be added automatically after resources created, so users don't have to look at the documentation when they want to change the stop behavior, whether it's production env or non-production env;
2. For the stability of production, set walrus.seal.io/stoppable=false by default.
3. It only supports adding the stoppable label to the resources below the non-production env, I think it's because in the 0.4 design, the stoppable label of resources was stopped=false by default, this misses the production environment.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 918a699c606f64575b1ac86f58c93ae899c141c0
- UI version: dev-3f29d01

**Test Result:** pass

- Add walrus.seal.io/stoppable=false to production environment: pass
- Remove the walrus.seal.io/stoppable label when cloning and exporting resource: pass
<img width="1001" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fa16ac03-1233-46e1-b8e7-24ba6d16b7ae">
