### ISSUE TITLE
Supports previewing changes before upgrading resources

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1786]
**Describe the solution you'd like**
1. Supports `terraform plan` to preview changes before upgrading resources and allows confirmation before applying them.(or "upgrade preview" to make it easier for the app team to understand?);

2. Provides support for configuring auto-apply in environment settings, with the option to enable auto-apply by default (or 'enable upgrade preview' for easier comprehension by the application team) and set to disable by default.

How to make it easier for the app team to understand, which requires extra consideration.

**Comment by Finenyaco** [comment]
Verified in 96792e2d3b2c3b1eae368faeb3c2690f91fbffc5.
