### ISSUE TITLE
Panic caused by method  validateConnector

### ISSUE THREAD

**Issue by 592146505** [seal-io/walrus#1801]
**Describe the bug**
kubeConfig点击保存失败
**Steps to reproduce**
1. Go to 'New Kubernetes Connector' Page
2. upload kubeConfig
3. click `save button`

**Result**
500 Internal Server Error

**Expected behavior**
save  success 

**Environment**
- Walrus version: dev<c7df6180>

**Additional context**

** Solution**

edit `pkg/apis/connector/basic_view.go`，add  param`model.ClientSet`

```go
func validateConnector(ctx context.Context, client model.ClientSet, entity *model.Connector) error {
	ops := optypes.CreateOptions{
		Connector:   *entity,
		ModelClient: client,
	}
 ...
}
```

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 2254204d25f1ee2a9714ae85b69b5b7dfb707543
- UI version: dev-04f141b

**Test Result:** 
Create connectors of different types and different environment types: pass
