### ISSUE TITLE
bump hermitcrab version

### ISSUE THREAD

**Issue by thxCode** [seal-io/walrus#1809]
- hermitcrab v0.1.2 support opentofu registry
- hermitcrab v0.1.3 expose measures for monitoring

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 278965251ef397a0f67ffab3c9348f4243d92c56
- UI version: dev-bb09fa3

**Test Result:** pass

<img width="1133" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ccc240d2-33b3-4467-b046-d6fc993439da">
