### ISSUE TITLE
Remove walrus.seal.io/stoppable label when exporting resources

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1814]
**Is your enhancement related to a problem? Please describe.**
Related to https://github.com/seal-io/walrus/issues/1765, now we will automatically add the stoppable label to resources after they are created.

If the label is exported together when the resource is exported, stoppable's expectations are inconsistent when applied to other types of environments, such as exporting from development and then import to production.

**Describe the solution you'd like**
Remove walrus.seal.io/stoppable label when exporting resources.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 645047fbb578508e9b8ab46353195be7de52f22e
- UI version: dev-6762e0b

**Test Result:** pass
