### ISSUE TITLE
Fail to deploy a containerservice

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1833]
**Describe the bug**

**Steps to reproduce**
1. Create a resource
2. Use template, choose kubernetes-containerservice v0.2.1
3. Input image=nginx
4. Save

**Result**
<img width="680" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/5cb08544-696c-4487-8b42-42db92a2b13f">

**Environment**
- Walrus version: main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 1e59b4feaae335bfa20cbfa170908396806ca7b5
- UI version: dev-437b352

**Test Result:** pass

<img width="2383" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/bf3e2b21-c435-40c4-9b32-b22c74b0ef4c">
