### ISSUE TITLE
Provide Walrus File samples

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1836]
**Is your enhancement related to a problem? Please describe.**
Provide a list of applications that can be deployed using walrus file in the UI

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a12b753f2e823aa7a7456110215dceed4da46ba1
- UI version: dev-07fa8db

**Test Result:** 

Using different rds names for `gitea-postgres` and `nextcloud-mysql` would be better.

<img width="1338" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ef980eca-f4ec-4ce9-94ec-7e0ec3ba45e3">
<img width="1330" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f209220c-3d6c-426b-af29-7a49491644d7">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 92b986390ec6ebc79d72efde4762453084c236a1
- UI version: v0.5.0-rc1

**Test Result:** pass
<img width="976" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3ee7d80d-b5a3-449c-ae0f-0a9f38ed728f">
<img width="995" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b8e769ad-5496-4812-9e6c-e17811618b38">
