### ISSUE TITLE
Incorrect resource statistics for dashboard

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1838]
**Describe the bug**

**Steps to reproduce**
1. Create some resources using template.
2. Create some resources using resource definition.
3. Go the dashboard and check the statistics.

**Result**

1. Incorrect resource statistics for dashboard
<img width="2465" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/23db6ff1-9644-4215-9422-457c74a73849">

2.The concept of service has been discarded.
<img width="532" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/37268a75-0d8a-4aeb-8190-1ca7a410f5ef">

**Expected behavior**

**Environment**
- Walrus version: main 3d6c9b2deb4970b456b6eff301c158e7543645db
- UI version: dev-c7e7d3b

**Additional context**

**Comment by gitlawr** [comment]
Should be fixed in main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8c258fa00a3e8c3f2895a5cfb7159ca2b5d7fc1f
- UI version: dev-88faa21

**Test Result:** pass

<img width="420" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b11b8395-85be-49e8-bb18-d98364a6736d">
