### ISSUE TITLE
Using a text editor in the terminal leads to a disconnection

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1863]
**Describe the bug**

Using a text editor in the terminal leads to a disconnection

**Steps to reproduce**
1. Create a resource using 'kubernetes-containerservice' template.
2. Connect to the terminal and install 'vim'.
3. Edit a file using vim.

**Result**

1. Connection disconnected.

https://github.com/seal-io/walrus/assets/26084756/8ec75f47-8339-4e60-a743-c1ba8db40809

<img width="1964" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/459406f9-d744-4433-abb6-40c6c77ebe11">

3. After reconnecting, repeat this operation several times. Eventually, the terminal cannot establish a connection.

The connection, interrupted abnormally, is not released, resulting in the inability to establish a new connection.

```
2024-01-11T03:38:21.413Z	D	api	429 | HTTP/1.1 |        0 B |       60 B |  5.000980014s |   192.168.227.1 | BS      /v1/projects/495611289394012930/environments/495611289410790146/resources/495616778429326082/components/495622011863753474/exec?key=default-local%2Fnginx-zq9qr-5d444cfdf6-m7dl5%2Frun%2Frun-0-nginx&shell=bash
```

**Expected behavior**

**Environment**
- Walrus version: main 937ca0fd19efd0e7137164f5b81c511f160426b2
- UI version: dev-6762e0b

**Additional context**

**Comment by thxCode** [comment]
1. @Finenyaco , I cannot reproduce with https://hub.docker.com/r/puritys/vim/tags
2. @hibig  the terminal cannot support `ESC` keyboard event, because switching VIM control mode from edit mode needs `ESC`.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 942e758b93603e9ad40f9da90260c30af5ea350b
- UI version: dev-b511a81

**Test Result:** pass
