### ISSUE TITLE
Remove svc resource output suggestion in UI

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#1875]
**Describe the bug**

There is no service any more, do not suggestion svc when referring resource output

**Steps to reproduce**
Create a new resource , fill form with ${

**Result**

`svc` shows

<img width="1667" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/199accf4-5308-40ff-93a2-ca789aac1292">

**Expected behavior**

Do not show svc

**Environment**
- Walrus version: main

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main f287a04a0e0e04715f6b161ba77407d0e03d563e
- UI version: dev-b6cc5ea

**Test Result:** pass

<img width="597" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/14a18107-a436-4dfa-9a84-d272c938bbc2">
