### ISSUE TITLE
Update opentofu deployer to stable

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1879]
Update to stable release and verify.

**Comment by thxCode** [comment]
sealio/opentofu-deployer:[v1.6.0-seal.1](https://hub.docker.com/layers/sealio/opentofu-deployer/v1.6.0-seal.1/images/sha256-8e8da01c31ffed86474025f40f6e563e31e263da73b56b243c3a0f3104190942?context=explore)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Test Result:** pass

<img width="629" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/45a54533-57a6-4303-a4c5-bf053ac7b22f">

<img width="692" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e5bcf09a-bf47-4730-be86-01ec3356a9be">
