### ISSUE TITLE
Resource configuration missing after editing workflow steps

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1891]
**Describe the bug**

Resource configuration missing after editing workflow steps

**Steps to reproduce**
1. New a workflow and add a `Deploy Resource` step.
2. Edit the step.

**Result**

1. Missing resource configuration after editing the step.

https://github.com/seal-io/walrus/assets/26084756/63d5ff84-298f-456e-aebb-85fbcd09fcb1

**Expected behavior**

**Environment**
- Walrus version: main f41cb2758ccafbd4e458c1b171345b1987aa3247
- UI version: dev-2c4d8f3

**Additional context**

**Comment by aiwantaozi** [comment]
Could not reproduce with main abdb301

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a12b753f2e823aa7a7456110215dceed4da46ba1
- UI version: dev-07fa8db

**Test Result:** 

Could not reproduce this issue with the latest main version.

But there has been another issue. After adding a 'Deploy Resource' step and editing again, the default values for disabled parameters will disappear.

https://github.com/seal-io/walrus/assets/26084756/bd0c5d4d-627f-4650-9cac-5a6da8a064d1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 92b986390ec6ebc79d72efde4762453084c236a1
- UI version: dev-21d34af

**Test Result:** Some values are still missing after editing.


https://github.com/seal-io/walrus/assets/26084756/32ada8fc-0919-4187-8042-f9f16c4e8421

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-a9c973f

**Test Result:** pass
