### ISSUE TITLE
The 'builtin-containerservice' resource definition does not display the configuration of the container

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1893]
**Describe the bug**

The 'builtin-containerservice' resource definition does not display the configuration of the container

**Steps to reproduce**
1. Go to resource definition page.
2. View the `builtin-containerservice` definition.

**Result**

1. Didn't show the configuration of container.
<img width="2438" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1a3fe237-70ba-4246-8287-8051fe6a7ba2">

**Expected behavior**

Show the  configuration of the container.

**Environment**
- Walrus version: main f41cb2758ccafbd4e458c1b171345b1987aa3247
- UI version: dev-25ace35

**Additional context**

**Comment by hibig** [comment]
1. There  is at least one item in template containers property.
<img width="865" alt="截屏2024-01-15 16 32 15" src="https://github.com/seal-io/walrus/assets/24664190/5d77cc25-d41d-4ae3-932e-7d87abf6d7b6">


Result:

1. The attributes is undefined, in the matching rules.


<img width="873" alt="截屏2024-01-15 16 30 47" src="https://github.com/seal-io/walrus/assets/24664190/dfd913e0-158d-4b0a-a6ad-02514e55b32a">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 42f6b1e6cbcd105e9e99ea8badacace1a799c043
- UI version: dev-2fca30f

**Test Result:** 

Container is displayed, but the default value is missing https://github.com/seal-io/walrus/issues/1898.

<img width="2427" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/2241dfcb-264d-403a-bc71-5c7c189d3582">
