### ISSUE TITLE
No default values for built-in resource definitions

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1898]
**Describe the bug**

**Steps to reproduce**
1. Go to resource definitions page.
2. View the built-in resource definition.

**Result**

1. No default values for built-in resource definition.
<img width="2553" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/de753a30-71b8-49d8-9aa1-41ebf9e4d80b">

**Expected behavior**

**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-567aeb4

**Additional context**

1. Create the same definition manually and default value are shown.
<img width="2553" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/19d47947-76ed-4a72-8fb1-9f202d113594">

**Comment by aiwantaozi** [comment]
Can't reproduce in 8ff16bf

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 0f1cc5f1584deeec4cd890ef1a18f529294006d2
- UI version: v0.5.0-rc1

**Test Result:** pass
