### ISSUE TITLE
Unable to add environment type selector in resource definition matching rule

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1904]
**Describe the bug**

**Steps to reproduce**
1. New a resource definition.
2. Add a selector in the matching rule and save.
<img width="846" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ee9e4b7f-ab56-43de-87e0-26169ec018f3">

3. Check the resource definition.

**Result**

1. No selector returned.
<img width="1078" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/06affdc5-c69d-4692-b66d-84320127f8e8">

<img width="801" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7a7e85c9-d894-482c-b21d-47dca6bc382f">

**Expected behavior**

**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-567aeb4

**Additional context**

**Comment by gitlawr** [comment]
@hibig EnvironmentType -> EnvironmentTypes

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-7590f46

**Test Result:**  Add one more empty environment type.

<img width="704" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d83868ed-5712-4cfa-a444-40f2f74d518d">

<img width="1069" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/67ae17fb-9dae-4ec2-aaba-12613df8ce2d">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-7590f46

**Test Result:** pass

Cannot use the definition created in the old version. Otherwise, it will result in adding an empty item.

<img width="1154" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9ec3c2d8-73a4-4917-b043-41f925a3de56">
