### ISSUE TITLE
Database seeding through text failed

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1919]
**Describe the bug**

Database seeding through text failed

**Steps to reproduce**
1. New a resource using template `kubernetes-mysql@v0.2.1` or  `
kubernetes-postgresql@v0.2.1` and seeding with text.
2. Check the tables after seeding.
<img width="1264" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a246f2d3-7a78-492c-a35d-8f1dcb50406b">

**Result**

1. No init-sql pod.
<img width="1164" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5643aff0-4f38-426e-9395-7475481772be">

**Expected behavior**

**Environment**
- Walrus version: main 42f6b1e6cbcd105e9e99ea8badacace1a799c043
- UI version: dev-2fca30f

**Additional context**

Seeding through url.
<img width="1028" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b6ceaa2e-da76-4fa1-a004-501b8b32c427">

**Comment by thxCode** [comment]
https://github.com/walrus-catalog/terraform-kubernetes-postgresql/releases/tag/v0.2.2
https://github.com/walrus-catalog/terraform-kubernetes-mysql/releases/tag/v0.2.2

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 918a699c606f64575b1ac86f58c93ae899c141c0
- UI version: dev-8062a50

**Test Result:** 
- builtin/kubernetes-postgresql@v0.2.2: pass
- builtin/kubernetes-mysql@v0.2.2: pass
