### ISSUE TITLE
Unify settings for disabling built-in catalog and resource definitions

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1920]
**Is your enhancement related to a problem? Please describe.**
Now we have two settings to control disabling built-in catalog and resource definitions.
It looks scattered. If we disable built-in catalog and enable built-in definitions, it doesn't make much sense.

**Describe the solution you'd like**
Use a single setting to control both.

If it's enabled, both built-in catalog and definitions are enabled. Vice versa.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 474911154e649e2811e39f28c6eb2573ab0b9f92
- UI version: dev-7449733

**Test Result:** pass
<img width="750" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7e595ee6-a915-40d2-a529-3de6a6d3b091">
