### ISSUE TITLE
Cannot access published endpoint in the local environment

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1932]
**Steps to reproduce**
1. Install Walrus: `docker run -d -p 80:80 -p 443:443 -p 30000-30100:30000-30100 --privileged sealio/walrus:v0.5.0-rc1`
2. Create a containerservice with nginx image, 80:80 port
3. Wait until the deployment succeeds and access the endpoint.

**Result**
The endpoint is inaccessible.

**Environment**
- Walrus version: v0.5.0-rc1

**Additional context**
It's using the internal IP of the walrus server container. It works when changing the IP to the Walrus server address.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 9a4516ef8771ed0bdce4acb990f084aa4e9a2a11
- UI version: dev-88faa21

**Test Result:** pass

<img width="1371" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f9963d0d-ae92-4c49-8f26-76b4e14516df">

<img width="2361" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/92da6319-3cd9-4a9c-9f89-49a7dfde5211">
