### ISSUE TITLE
Double click on the deploy button results in two API requrests

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1939]
**Steps to reproduce**
1. Create a containerservice
2. double click on the save and deploy button

**Result**
<img width="619" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/bd913f3f-9dc6-4f8d-b3bd-3f35240386ae">

**Environment**
- Walrus version: v0.5.0-rc1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Test Result:** pass
