### ISSUE TITLE
Show one configuration in revision change history

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1948]
**Is your enhancement related to a problem? Please describe.**
![image](https://github.com/seal-io/walrus/assets/5697937/ac458e5d-d43b-4cbe-928a-d8fb018d044e)

On rollback or viewing change history of a revision, we show two configurations which can be confusing.

**Describe the solution you'd like**
Show only one configutaion that take effects

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-88faa21

**Test Result:** pass

Remove runtime configuration.

<img width="837" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e8be8fd8-e8d5-40cf-89b2-43e83ccbb5a1">
