### ISSUE TITLE
cli decrease the timeout for server reachable check

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1960]
**Is your enhancement related to a problem? Please describe.**
Now CLI configured with an unreachable server takes a long time to timeout. 
Need to decrease the timeout for server reachable check.

**Comment by Finenyaco** [comment]
**Environment**
- CLI version: 73e6ce88f4205e030d30ff4276e82d687c0ccdd0

**Test Result:**
When unable to connect to the server, about 20-second waiting period is required.
```
 ~/.walrus/ time walrus version
access https://walrus.tsfxwx.com failed
walrus version  0.05s user 0.03s system 0% cpu 20.202 total
```

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-8ceaed8

**Test Result:** 

The current response takes 10 seconds. The timeout duration can be further reduced.

<img width="544" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e321142a-29ba-4de3-8909-7d31581b6dce">

**Comment by aiwantaozi** [comment]
This is caused by the office network(proxy).

Under the office network, could access the unreachable network.
![Image](https://github.com/seal-io/walrus/assets/5936271/90f49920-dc05-42b1-96d2-513f4c2b81ab)

After switching to the mobile network, couldn't access it, and the walrus cli response time is around 3 second
![Image](https://github.com/seal-io/walrus/assets/5936271/0cf205b0-b14d-441c-b108-6f634ec81df3)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-94aee09

**Test Result:** 

- When the domain name cannot be resolved
```
 ~/seal/ time w version
clientVersion:
  version: main
  gitCommit: 4c1b4a42d2281ef308519aed71c0dac46cff6c87
  isDevVersion: true
walrus version  0.04s user 0.01s system 50% cpu 0.106 total
```

- When the domain name can be resolved but cannot be connected
```
 ~/seal/ time w version
clientVersion:
  version: main
  gitCommit: 4c1b4a42d2281ef308519aed71c0dac46cff6c87
  isDevVersion: true
walrus version  0.04s user 0.01s system 1% cpu 3.058 total
```

- When the address can be connected, but the Walrus service is inaccessible.
```
 ~/seal/ time w version
clientVersion:
  version: main
  gitCommit: 4c1b4a42d2281ef308519aed71c0dac46cff6c87
  isDevVersion: true
walrus version  0.04s user 0.03s system 0% cpu 10.143 total
```
