### ISSUE TITLE
Failed to deploy docker postgresql  resource using the built-in resource definition

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1970]
**Describe the bug**

Failed to deploy docker postgresql using the built-in resource definition `postgresql`.

**Steps to reproduce**
1. Setup Walrus with docker mode.
2. Create a posgresql resource using the built-in resource definition `postgresql`.
3. Check the deployment result.

**Result**

1. Failed to deploy.
<img width="1046" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/228922dc-2b6b-46a4-adfa-3556325dfecc">

2. The engine version is incorrect.
<img width="2404" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e5a78381-53b4-4905-8a02-c690f12f3fdb">

**Expected behavior**

Deploy successfully.

**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Test Result:**

Similar issues exist in other fields. For example, in the `container` definition, the 'Accept Changed' attribute in Kubernetes was originally modifiable, but now it is not.

<img width="1262" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e7b3d54b-2a16-4ea1-9dc1-f869aba3a218">

**Comment by shanewxy** [comment]
> **Environment**
> 
> * Walrus version: main [98e5445](https://github.com/seal-io/walrus/commit/98e5445080de1e1017db16951dd12d8e1e52b27f)
> * UI version: dev-3fcbabe
> 
> **Test Result:**
> 
> Similar issues exist in other fields. For example, in the `container` definition, the 'Accept Changed' attribute in Kubernetes was originally modifiable, but now it is not.
> 
> <img alt="image" width="1262" src="https://private-user-images.githubusercontent.com/26084756/298001572-e7b3d54b-2a16-4ea1-9dc1-f869aba3a218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTU3NDYsIm5iZiI6MTcwNTY1NTQ0NiwicGF0aCI6Ii8yNjA4NDc1Ni8yOTgwMDE1NzItZTdiM2Q1NGItMmExNi00ZWExLTlkYzEtZjg2OWFiYTNhMjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZmZhYmY5ZTQ0YWU5NDY3MTc0MGM5Y2RkMDFiODYyMDJmNzJkZjJlMjlmYmI2MDUxZjNkOTFjZWU0ZGNkYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19xBzoQBOEgFVkneWZGaI0_4f7GW0LQfDCmwk9A0Yyo">

Fixed engine version. 

But as for 'Accept Changed', it is a readonly attribute in docker-containerservice, so that it will result in readonly in merged resource definition.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:** 

- postgresql: pass
<img width="2466" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/190b16e8-4ce9-4897-8d88-39f8ad910def">

- containservice: But 'Accept Changed' can be set to true now. It is supposed to be immutable according to the design.
<img width="2120" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/aeca054e-0188-4d28-a23a-1c1378e11f01">

**Comment by thxCode** [comment]
we are going to process merging read-only attribute in resource definition, which means the built-in containerservice is not allowed `Accept-Changed`.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 3806cbeb980963a23e83bf42b8ac3b15c287fbba
- UI version: v0.5.0-rc2

**Test Result:** Verified containerservice resource definition: pass

<img width="1199" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f0dae850-5328-4b88-b0c4-6313a7dc6624">
