### ISSUE TITLE
Change title editing resource to be cloned

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1976]
<img width="1361" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/4c1e59f2-a2af-434b-a1be-649438a00193">

**Steps to reproduce**
1. Clone resources
2. Edit one of the configuration.

**Environment**
- Walrus version: main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 918a699c606f64575b1ac86f58c93ae899c141c0
- UI version: dev-8062a50

**Test Result:** pass

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1ec1ab36-527d-4778-aaa1-6b92d9419b61">
<img width="2402" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ace83495-ab06-43cf-af1d-a69153139d58">
