### ISSUE TITLE
UI add dark mode

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1980]

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main f1ad5a6dd0a90bd792b6222337a98d37b89ceb7b
- UI version: dev-22fdb32

**Test Result:**

Please continue to optimize the following two scenarios.

<img width="1197" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/756f0abe-0ef3-45a9-ba61-1aabbb1c18eb">

<img width="920" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1b9906c0-9b3e-4ceb-866a-4de72b75a052">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 61fe2d23f46237867cf199c44a3275ee71b7805d
- UI version: dev-b878771

**Test Result:** pass
