### ISSUE TITLE
rename operation menu

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2021]
Update `Operation` to `Operations`

**Environment**
- Walrus version: v0.5.0-rc3

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a803edf588fc3dc8024ebdb4745b184b3b40bba7
- UI version: dev-186c2e0

**Test Result:** pass


<img width="1168" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/17b24a2c-0d7a-4aec-9498-cfecbdb425e4">
