### ISSUE TITLE
UI label for kubernetes connector name

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2023]
Change `Cluster Name` to `Name` on creation

<img width="1132" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/700a3f7c-e0be-4920-bb36-f975a877e07e">

**Environment**
- Walrus version: v0.5.0-rc3

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a803edf588fc3dc8024ebdb4745b184b3b40bba7
- UI version: dev-186c2e0

**Test Result:** pass

<img width="1003" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0642008f-cd7f-40f5-8057-b5be075da709">
<img width="908" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b6b60558-828a-429f-9998-c9d0428a097e">
