### ISSUE TITLE
Search users with name shows unexpected result.

### ISSUE THREAD

**Issue by alexcodelf** [seal-io/walrus#2024]
**Describe the bug**

Incorrect result when querying users

**Steps to reproduce**
1.  Create four users `admin`, `test`, `manager`, `ad`
2. Search users with keyworkds `n`

**Result**

<img width="3008" alt="image" src="https://github.com/seal-io/walrus/assets/85595852/5f6385f3-4891-482c-8ca5-68853f2b68eb">

**Expected behavior**

Only shows manager and admin, the name contains key words.

**Environment**
- Walrus version: v0.5.0-rc3

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 7bb79389ab0436969f4c4214e38918ee6c6e9070
- UI version: dev-1be55ba

**Test Result:** pass
