### ISSUE TITLE
Update toolbar hints in dependency graph

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2026]
<img width="179" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/c6d28484-4bc0-43d8-bbc3-864660656e53">

Make the following changes:
fit view -> Fit View
show/hide subresources -> Show/Hide Components

**Environment**
- Walrus version: v0.5.0-rc3

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a803edf588fc3dc8024ebdb4745b184b3b40bba7
- UI version: dev-186c2e0

**Test Result:**  hide Components -> Hide Components

<img width="577" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6c7fe493-44f8-4665-b4e4-7663288d6806">


<img width="385" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6bfb15aa-1480-4f52-a07c-abeca3547a65">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a803edf588fc3dc8024ebdb4745b184b3b40bba7
- UI version: dev-0959267

**Test Result:** pass

<img width="535" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5a22feac-5cc5-497e-9324-03e49ca2137d">
