### ISSUE TITLE
Update run workflow button

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2028]
<img width="1337" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/8a0804f1-a62a-4fa4-98f1-aa3c13557c94">

Run a workflow, change the `Save` to `Run`.

**Environment**
- Walrus version: v0.5.0-rc3

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a803edf588fc3dc8024ebdb4745b184b3b40bba7
- UI version: dev-186c2e0

**Test Result:** pass

<img width="844" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fa627874-2f2f-4108-8925-86b6660c5ec3">
