### ISSUE TITLE
Enhancement for defining shared costs

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#204]
**Version:** main
**UI:** dev-49c4df8
**Commit ID:** 94ba340099ffa07f88e62c12bef48af603a89558
**Env:** MacOS 13.1, Apple M2

Currently, if you want to define the shared costs, you must exclude the item in the filter manually. This interaction is not concise enough.  Can we automatically exclude items that share costs?

<img width="939" alt="image" src="https://user-images.githubusercontent.com/26084756/227409570-62b9f2c3-3c9a-4b8b-b202-e2ced9d10e33.png">

**Comment by gitlawr** [comment]
No more valid in the latest version
