### ISSUE TITLE
Cannot go to current project view in an environment view

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2053]
**Steps to reproduce**
1. Go to the default environment view
2. Open project dropdown and choose the default project
<img width="810" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/b28cdded-fe9b-4158-8234-7dbc583c6d43">

**Result**
It does not switch to the project view

**Environment**
- Walrus version: v0.5.0-rc4

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e92cde6256262c9671c9d51475f0bee8669f6628
- UI version: dev-78d87e4

**Test Result:** pass


https://github.com/seal-io/walrus/assets/26084756/53f43d8b-a7f3-4aca-a3e8-1fc0a4ffb158
