### ISSUE TITLE
Support configuring server options for local Walrus

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2062]
**Is your enhancement related to a problem? Please describe.**
Be able to configure [server options](https://seal-io.github.io/docs/deploy/options) when running `walrus local install`. e.g., set builtin-catalog-provider to gitee.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-95fef06

**Test Result:** pass

```
root@iZbp14mscl82upj4amm48eZ:~# walurs local install -e SERVER_BUILTIN_CATALOG_PROVIDER=gitee
Installing...
Checking readiness...
Walrus CLI is configured.
```

<img width="816" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0b298e9f-e68a-40ee-98a0-1a8ef2fcd437">


Note: The Docker extension is not available when using the `-e` flag.
