### ISSUE TITLE
Add export button to single resource operations menu

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#2065]
Version: v0.5.0
Description:
Currently the export button is only available in the multi-select menu. We should add it to the operation menu of single resource too.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main eb8e29d68c15d16e0fe6b1bc95dca3bdab96a454
- UI version: dev-bb86dbc

**Test Result:** pass

<img width="2211" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b932ebb6-c52c-44b2-adaf-53ce064542c9">
