### ISSUE TITLE
Support Walrus cli in Windows OS

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#2069]
Currently Walrus cli only has MacOS and Linux versions. Windows should also be supported.

**Comment by thxCode** [comment]
<img width="1094" alt="image" src="https://github.com/seal-io/walrus/assets/3394724/e477b606-d390-4aa9-b091-02761d3c4340">

there are lots of paths util cannot recognize windows path, I will make another PR to modify this.

**Comment by Finenyaco** [comment]
Windows OS: arm64 win11

Verified in 5d939ccf90935cc12b8b7cd7d28e5bd255c22df5.
