### ISSUE TITLE
The leading and trailing spaces in the input box make the parameter ineffective.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#2077]
**Describe the bug**

**Steps to reproduce**

**Result**

**Expected behavior**

Trim the leading and trailing spaces from the input box by default.

**Environment**
- Walrus version:

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4f06127b541a926b603ebff57960d887a8bb7264
- UI version: dev-2140d7c

**Test Result:**

The current text area does not support trailing line breaks. 

Does the text area need to have this restriction?

<img width="527" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/aa424462-6fce-4dce-9766-e086a12273cb">

<img width="562" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8d538041-f4f3-4697-902b-400ff3df4bcd">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 4f06127b541a926b603ebff57960d887a8bb7264
- UI version: dev-75969a4

**Test Result:** pass
