### ISSUE TITLE
Fix the walrus image tag in walrus-images.txt

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#2080]
**Describe the bug**
The walrus image tag in walrus-images.txt is still v0.4.0:
![image](https://github.com/seal-io/walrus/assets/42955482/4575ad53-ac53-4948-96b0-5269574c77ff)

**Expected behavior**
Fix the walrus image tag.

**Environment**
- Walrus version: v0.5.0

**Comment by gitlawr** [comment]
Verify in rc

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1-rc2

**Test Result:** pass

<img width="612" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3389babc-5d9a-4adf-9039-4d3a045ececc">
