### ISSUE TITLE
Enhancements of not being able to get the server version

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2103]
**Is your enhancement related to a problem? Please describe.**

When failed to get to the Walrus server version, it's also unable to view the current version of the Walrus CLI client.
```
root@ip-192-168-1-125:/opt/walrus# w version
got not found response from https://xxx/debug/version, failed to decode response body: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html>
<he|..., bigger context ...|<html>
<head><title>404 Not Found</title></head>
|...
```

```
 ~/seal/ w version
unexpected status code 503 from https://192.168.50.182/debug/version, <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Describe the solution you'd like**

1. Even though it's failed to get the server version, the client version should still be displayed.
2. Optimize the logs for when getting the server version fails to make it more understandable.

**Describe alternatives you've considered**

**Additional context**

clientVersion:
  version: main
  gitCommit: 5d939ccf90935cc12b8b7cd7d28e5bd255c22df5

**Comment by thxCode** [comment]
also consider https://github.com/seal-io/walrus/issues/2073

**Comment by Finenyaco** [comment]
**Test Result:** Pass

Did not print server version when failing to retrieve it.
```
 ~/ w version
clientVersion:
  version: main
  gitCommit: 3b93fab7fcdac5c5ba61984ee7431021a7593592
```
