### ISSUE TITLE
List map string field do not trigger validate.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#2105]
**Describe the bug**

**Steps to reproduce**
1. Set the list-map-string field as required.
2. Create a resource using the template and set the value to empty.
3. After clicking the "Save" button, there is no validation message for the field.

**Result**

Submit successfully.
**Expected behavior**

Can't submit the form data, and there is validation message.

**Environment**
- Walrus version:

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-95fef06

**Test Result:**

Cannot edit the value now.
https://github.com/seal-io/walrus/assets/26084756/8106aec5-406a-4a76-9db3-023348502a1e

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-b3f75f4

**Test Result:**

Validation fails for variables of type `may(any)`.

<img width="645" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6403c873-6f84-4c18-a338-7e7e4fb97817">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-e738a7a
**Test Result:**

list(map(string)): pass
map(any): pass
list: failed, no validation on the UI.

<img width="341" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c17b98f3-b453-4e9d-8f4d-7ad1be5920ae">
<img width="623" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8872c22b-3a97-4daa-a074-b762406b6411">

<img width="636" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/4d106a3d-d2ae-4415-860f-fb7ab58d6f50">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-3da39a5
**Test Result:** 

When creating or editing resources, the list-type properties are still not validated.

https://github.com/seal-io/walrus/assets/26084756/82fb8710-edc1-4257-8668-cb6601d06be3

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-1b96807
**Test Result:** pass

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: v0.5.1-rc1
**Test Result:** 

The `required` for map(string) type is not taking effect.

<img width="1158" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/aa924919-7925-449e-9506-334b85fcc3e6">


![Image](https://github.com/seal-io/walrus/assets/26084756/fdf02a03-f311-4265-bdb1-5f425457b74c)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-41c46ad

**Test Result:** pass
<img width="1244" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/bf3ee80d-6dc2-46cb-a17a-72ad31c0f282">
