### ISSUE TITLE
Incorrect merged default values for map(string) type variables of resource definition

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2109]
**Describe the bug**

**Steps to reproduce**

1. Template definition:
<img width="487" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3af76159-f0ea-4fdd-bcbf-bae9b19a60f0">

2. Check the resource definition:
<img width="1124" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ba8f9133-8351-47c3-bc81-277f974e8e11">

**Expected behavior**

**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: v0.5.1-rc1

**Additional context**

**Comment by thxCode** [comment]
https://github.com/seal-io/walrus/pull/2108 supports generated nil default if all defaults are not the same.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ddec5a82d6ee0b81d4d088cc5dfef8f067eb77f6
- UI version: dev-be9a1a4

**Test Result:** pass, but further enhancements are needed for the computed attributes of map-type variables. https://github.com/seal-io/walrus/issues/2113
