### ISSUE TITLE
Could not reference environment level variables in workflow

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#2115]
**Describe the bug**
Could not reference environment level variables in workflow.

**Steps to reproduce**
1. Create an environment level variable;
2. Create a workflow, add a Deploy Resource task, choose the same environment, try to reference the variable that created earlier.

**Result**
Could not reference the environment variable in workflow.

**Expected behavior**
Can reference the environment variable in workflow.

**Environment**
- Walrus version: v0.5.0

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b926a09a84b4ea20551cc9ded7a0d1f57b9c4f68
- UI version: dev-2ae60e3

**Test Result:** pass

<img width="980" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3b6dd301-e963-4816-aa96-9d966d42224e">
