### ISSUE TITLE
Update PostgreSQL templates

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2116]
**Is your enhancement related to a problem? Please describe.**

**Issue 1: The default value `Class` should be updated. `rds.pg.s2.large` is unavailable.** https://www.alibabacloud.com/help/en/rds/apsaradb-rds-for-postgresql/primary-apsaradb-rds-for-postgresql-instance-types

<img width="1973" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5b5ae13d-2626-4474-a175-ed7f6d6bde4a">

<img width="762" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/37ec419b-1db3-46df-8798-1ea4e9f9b2ca">

**Issue 2:  The version of different PostgreSQL templates are currently inconsistent.**
- docker:   16
- kubernetest: 15
- alicloud: 15
- aws: 15

**Describe the solution you'd like**

1. Update the resource class.
2.  Unify the postgresql versions.

**Describe alternatives you've considered**

**Additional context**

**Comment by shanewxy** [comment]
bump to v0.3.1

**Comment by Finenyaco** [comment]
The default value for instance class in schema.yaml was not updated. 

@aiwantaozi  Can you please add a method to automatically update schema.yaml after modifying variables.tf?

<img width="1934" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/228c5e61-d3c0-4e48-85bd-ec8e84fc4870">

**Comment by Finenyaco** [comment]
Unable to import [terraform-aws-rds-postgresql](https://github.com/walrus-catalog/terraform-aws-rds-postgresql) v0.3.1

```
2024-02-05T11:51:13.873Z	D	api	201 | HTTP/2.0 |      134 B |      247 B |   11.354216ms |   192.168.247.1 | POST    /v1/templates
2024-02-05T11:51:15.322Z	W	template	recording syncing template 499297118507300610 schema failed: failed to get reference: v0.3.1
```

<img width="2461" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/33f7e3b9-1d09-4cad-a770-a992143d9225">

**Comment by thxCode** [comment]
@aiwantaozi  need something like `--override-defaults` to free us from schema struggle,  https://github.com/seal-io/walrus-template-template/blob/0b52993ea5ab2fdf9f193897e4c242941b1884ce/hack/lib/walrus-cli.sh#L72 .

**Comment by aiwantaozi** [comment]
Sure.

**Comment by thxCode** [comment]
> The default value for instance class in schema.yaml was not updated.
> 
> @aiwantaozi Can you please add a method to automatically update schema.yaml after modifying variables.tf?
> 
> <img alt="image" width="1934" src="https://private-user-images.githubusercontent.com/26084756/302272096-228c5e61-d3c0-4e48-85bd-ec8e84fc4870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDY1MzUsIm5iZiI6MTcwNzIwNjIzNSwicGF0aCI6Ii8yNjA4NDc1Ni8zMDIyNzIwOTYtMjI4YzVlNjEtZDNjMC00ZTQ4LTg1YmQtZWM4ZTg0ZmM0ODcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA3NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmY3YTI3OTc2NDQ3ZGFhNTViMGViMjUwZTg4N2IyMTAxZmIzYjJlZGEwZjRiM2RhZjBmYWE1NTFjODU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kfmGdJwXcZEgmhyfopcVi0sENEjRt6BZrS0cs6oDL0I">

terraform-alicloud-rds-postgresql:v0.3.2

**Comment by thxCode** [comment]
> If we just overwrite the default value, maybe not just default? There may be more scenarios: when the default is removed, needs to update the required fields; when the default is added, needs to update the required fields; when the variable only provider defaults, and it updates, need to update the guessed type. ...

let's discuss this in https://github.com/seal-io/walrus/issues/2122

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 700d971e404e208e929bcbb088ec974f07c871c0
- UI version: dev-7fa18e0

**Test Result:** pass

<img width="1578" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/7c960bef-bbc1-4a5c-b069-38ed8646534b">

<img width="1548" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/09c895c9-68f5-4089-8d95-838e7d0d4303">
