### ISSUE TITLE
The default value of the variable displayed by showIf is not displayed when editing a resource

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#2132]
**Describe the bug**
The default value of the variable displayed by showIf is not displayed when editing a resource.

**Steps to reproduce**
1. Create a resource using the template with the showIf configuration.
2. Edit the resource and try to trigger the showIf configuration.

**Result**
The default value of the variable displayed by showIf is not displayed.

**Expected behavior**
The default value of the variable displayed by showIf is displayed.

**Environment**
- Walrus version: v0.5.1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main e92cde6256262c9671c9d51475f0bee8669f6628
- UI version: dev-606a1a9

**Test Result:** pass


https://github.com/seal-io/walrus/assets/26084756/df4863c7-c943-4f0e-ac23-1bd57525ff75
