### ISSUE TITLE
local walrus stops after reboot

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2140]
**Steps to reproduce**
1. Install local walrus.
2. Reboot
3. Check local walrus container

**Result**
It stopped.

**Expected behavior**
It starts again after reboot

**Environment**
- Walrus version: v0.5.1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 0a3779654c43dfb1a5d3299c4862502a909f2878
- UI version: dev-c3de3bf

**Test Result:** Reboot the host and check the Walrus container, pass

<img width="449" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0e866130-2e71-47c5-920f-34e8590e8300">
