### ISSUE TITLE
Failed to get deployment logs: the server could not find the requested resource

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2206]
**Describe the bug**

**Steps to reproduce**
1. New a resource to deploy a google mysql instance.
2. View the deployment logs.

**Result**

1. Failed to get deployment logs.
<img width="878" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d4e54149-5a8b-47a1-a769-6c9f8f0a2b0d">

<img width="888" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ffdba5b0-6408-44fd-b414-26cef07fcdb2">

```
2024-03-07T12:20:01.769Z	D	api	200 | HTTP/2.0 |        0 B |        0 B |  1.415880115s |   192.168.216.1 | US      /v1/projects/503740965677225986/environments/503751901871921154/resources/503776165887006722/components?watch=true
2024-03-07T12:20:02.026Z	E	k8sctrl.deployer.tf	failed to get job pod logs	{"error": "the server could not find the requested resource (get pods tf-job-plan-503792589103749122-dlkm5)", "resource-run": "503792589103749122"}
github.com/seal-io/walrus/utils/log.logrSinker.Error
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/log/logr.go:67
github.com/go-logr/logr.Logger.Error
	github.com/go-logr/logr@v1.4.1/logr.go:301
github.com/seal-io/walrus/pkg/resourceruns/job.Reconciler.syncRunStatus
	github.com/seal-io/walrus/pkg/resourceruns/job/reconcile.go:86
github.com/seal-io/walrus/pkg/resourceruns/job.Reconciler.Reconcile
	github.com/seal-io/walrus/pkg/resourceruns/job/reconcile.go:47
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2024-03-07T12:20:02.027Z	I	k8sctrl.deployer.tf	succeed	{"resource-run": "503792589103749122"}
```

**Expected behavior**

**Environment**
- Walrus version: v0.6.1-rc1
- Template version: google-mysql@v0.1.0

**Additional context**

**Comment by aiwantaozi** [comment]
Couldn't reproduce

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 39304a76ab4b41f764ee0087ebaee793437efca4
- UI version: dev-ae07951

**Test Result:** pass

<img width="891" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f28fcd9a-06df-4129-9ee0-06651578ef45">



In 0a0f275bc92d1f7f379e5d97337b3362096fe508, it will display the plan logs if the duration large than 10mins.
<img width="887" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/ca2b2883-20d6-43f5-9be4-3d62d6db8bb2">
