### ISSUE TITLE
Change Token to API Key

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2241]
**Describe the bug**
Use consistent phrases in UI/CLI

UI
<img width="462" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/84616155-2394-42b7-8bc8-5b65830d3a14">

CLI
<img width="243" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/e2bf071b-7709-4181-8aaf-2c2efb56f83c">

**Environment**
- Walrus version: main

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main c6bba6b527201671bcf74167e17f4fdd4fcfa40d
- UI version: dev-db16ba4

**Test Result:** pass

- CLI:
<img width="410" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/91cf5864-18d6-4626-b43f-acc198a62b95">

```
Usage:
  walrus login [flags]

Flags:
      --api-key string       API key to communicate with server
  -e, --environment string   Environment for default use
      --insecure             Disable SSL verification
  -p, --project string       Project for default use
  -s, --server string        Server address, format: scheme://host:port

Global Flags:
  -d, --debug   Enable debug log
  -h, --help    Help for this command
```

- UI:
<img width="2461" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1d46e74e-57f0-44b7-a55e-0624fc987256">
