### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by menardorama** [seal-io/walrus#2273]
Hi,

Is it possible to use openidconnect in order to authenticate on walrus ?

I have tried to configure an oidc provider on cassdoor but this does not appear on the login page of walrus.

Thanks

**Comment by thxCode** [comment]
Hi, we will support OIDC out-of-box in next release instead of casdoor, keep watching us, thanks.

**Comment by menardorama** [comment]
Sounds great thanks
