### ISSUE TITLE
 Incorrect cost data when grouping by year

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#234]
**Version:** main
**UI:** dev-02ac8f1
**Commit ID:** 030e6f47cddfae278be486cfc2a9ecdc1c110f87
**Env:** MacOS 13.1, Apple M2

**Prerequisite:**
Have more than two months of data.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/26084756/227900880-a187da37-ebc8-4e95-9870-4d6a5db2dd12.png">

**Test Steps:**
1. Create perspective grouped by year.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/26084756/227900519-29514e29-8b4f-4d73-adf8-433abc225e37.png">

2. View the perspective.

**Test Result:**

1. The data is wrong.
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/26084756/227898796-c9f3d072-6009-4385-a2ba-46b4494a64fb.png">

**Comment by gitlawr** [comment]
No more valid in the latest version
