### ISSUE TITLE
Add project prefix to application cost rank on dashboard

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#263]
**Version:** main
**UI:** dev-6b34cfa
**Commit ID:** ae650fecff37239113667e9d7acf4fe0df7563c0
**Env:** MacOS 13.1, Apple M2

There is currently no way to distinguish which project the app belongs to.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/26084756/228702326-14ed99cf-7d19-484a-96d1-d8de434c9cfe.png">

The api response does not contain the project information now.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/26084756/228703505-e24b2a25-dbfb-4e83-a0a7-242a673b4f1f.png">

**Comment by gitlawr** [comment]
No more valid in the latest version
