### ISSUE TITLE
Deleting an instance affects other resources if the same namespace is used

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#288]
**Version:** main
**UI:** dev-41f67e7
**Commit ID:** 215ade7b2b903b6fb3eea78d17ac5cc274c53520
**Env:** MacOS 13.1, Apple M2

**Test Steps:**
1. Create application A and deploy resources as below, a namespace called `testwo` was created by this instance.
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/26084756/229082418-02ee370e-db32-457f-b103-41c4473b0a32.png">

2. Create another application B and deploy resources in `testwo` namespace.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/26084756/229081336-138df861-1039-4b15-8934-094a94e8d36c.png">

```
root@lbtest-control-plane:/# kubectl get all -n testwo
NAME                                   READY   STATUS    RESTARTS   AGE
pod/native-katydid-7bd79f8d6-5c6f6     1/1     Running   0          2m10s
pod/splendid-urchin-555bf89964-m2jlg   1/1     Running   0          3m59s

NAME                      TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/native-katydid    NodePort   10.96.109.244   <none>        80:31135/TCP   2m10s
service/splendid-urchin   NodePort   10.96.235.100   <none>        80:30315/TCP   3m59s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/native-katydid    1/1     1            1           2m10s
deployment.apps/splendid-urchin   1/1     1            1           3m59s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/native-katydid-7bd79f8d6     1         1         1       2m10s
replicaset.apps/splendid-urchin-555bf89964   1         1         1       3m59s
```

3. Delete the instance of application A. (check clear all resources)

**Test Result:**
1. This whole namespace is deleted. It affected the instance in application B.
``` 
root@lbtest-control-plane:/# kubectl get all -n testwo
No resources found in testwo namespace.
```

**Expected Result:**
It shouldn't delete resources of other instances.

**Comment by aiwantaozi** [comment]
Close since the environment namespace is managed by walrus now.
