### ISSUE TITLE
It does not show the resource namespace of the mysql module

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#352]
**Version:** main	
**UI:** dev-15bbc06
**Commit ID:** eee5b2bf47df3959fa8ca818b96cbc1ed7c02277
**Env:** Ubuntu 22.04 amd64

**Test Steps:**
1. Add a mysql module to app.
2. Deploy an instance.
3. View the instance resource.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/26084756/230392282-5a3450b1-5728-48bb-920c-f0b92fdfb2b2.png">

**Test Result:**

1. It did not show the namespace of mysql.
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/26084756/230391931-3898d709-9631-4483-a226-f7527e5c480b.png">

```
 ~/ kubectl get all -n myproject-mysql-web2-ins
NAME                         READY   STATUS    RESTARTS   AGE
pod/mysql-0                  1/1     Running   0          7m11s
pod/nginx-749dc754dd-fddq7   1/1     Running   0          7m22s

NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/mysql-headless   ClusterIP   None            <none>        3306/TCP       7m12s
service/mysql            ClusterIP   10.43.101.83    <none>        3306/TCP       7m12s
service/nginx            NodePort    10.43.108.156   <none>        80:32205/TCP   7m23s

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx   1/1     1            1           7m24s

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-749dc754dd   1         1         1       7m24s

NAME                     READY   AGE
statefulset.apps/mysql   1/1     7m13s
```

2. Check api response.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/26084756/230393422-fdcada06-6646-423c-bfe1-61cb3e2bc61a.png">

**Comment by gitlawr** [comment]
No more valid in the latest version
