### ISSUE TITLE
Support create cost bucket

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#388]
Now we only support some built-in groupBys, for example, a department use namespaces A, B, C, and another department use namespaces D, E, and F, which can't support user creating a perspective to view cost for these departments.

A cost bucket is one or more filters that collect data from a data source, which is more flexible. We need to support:

1. create/update/list/delete the cost bucket, cost bucket use filters to select resource cost
<img width="980" alt="image" src="https://user-images.githubusercontent.com/5936271/231107603-9c1af4d0-5ae9-4da0-ae3f-83f00f6e8c9c.png">

2. use cost bucket
while creating perspective, in the step defined cost unit, the user could use get the cost from one of the below sources.
   - cost buckets
   - defined the resource filter and groupBy
 in the step split share cost rule, the user could define multiple rules, and get the share cost from one of the below sources.
   - cost buckets
   - defined the resource filter and groupBy

**Comment by gitlawr** [comment]
No more valid in the latest version
