### ISSUE TITLE
Issues for app/project labels 

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#390]
**Version:** main
**UI:** dev-debfa1a
**Env:** MacOS 13.1, Apple M2
**Commit ID:** eee5b2bf47df3959fa8ca818b96cbc1ed7c02277

**Test Result:** 
**Issue 1:** If grouped by Label/Application, resources with the same app name in different projects cannot be distinguished.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/26084756/231105051-45804ae4-7919-4c66-b345-df2784935d4d.png">

**Issue 2:** If modify the app name or the project name, it will display two different apps or two different projects.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/26084756/231118833-39743163-6843-4da7-87a1-8b7ee64d2bea.png">

```
root@lbtest-control-plane:/# kubectl get pod/mydeploy-57964f7f44-9vkpk -n testproject-myapp-myins -o jsonpath="{.metadata.labels}"
{"app":"mydeploy","pod-template-hash":"57964f7f44","seal.io/app":"myapp","seal.io/environment":"lbtest","seal.io/project":"testproject"}
```

**Suggestion:** 
Use appID or projectID as labels. It is unique and it doesn't change with the name change.

**Comment by gitlawr** [comment]
No more valid in the latest version
