### ISSUE TITLE
Add the project name before the application name when perspective is grouped by app labels

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#391]
**Version:** main	
**UI:** dev-debfa1a
**Commit ID:** 91c2f0ef5ff2e0bb7c7f1b8ae3407526bcabce7f
**Env:** MacOS 13.1, Apple M2

**Prerequisite:**
1. Create two app with the same name in two different projects.
2. Deploy instances and wait for cost data to be fetched.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/26084756/231130662-a017554e-dc1c-44a7-b15a-e4d971e035ae.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/26084756/231130712-86eacf50-b24e-43c4-952d-e48614cf22f9.png">

**Test Steps:**
1. Create a perspective grouped by `Label/ Application`.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/26084756/231130383-730f6e85-a24c-48ed-8a03-6b314ee8d0b4.png">

2. View the perspective created in step 1.

**Test Result:**
1. The data of the two apps (project1/appa and project2/appa) is aggregated. (Issue 1 in https://github.com/seal-io/seal/issues/390)
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/26084756/231131790-f77bb5c2-212e-4b3f-95b1-990c4362834d.png">

**Suggestion:** 
Please add the project name before the application name to distinguish applications with the same name.
<img width="1831" alt="image" src="https://user-images.githubusercontent.com/26084756/231130054-62e21c79-a989-473d-ad55-016fdfc4427d.png">

**Comment by gitlawr** [comment]
No more valid in the latest version
