### ISSUE TITLE
Support offline installation

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#412]

**Comment by aiwantaozi** [comment]
For image part:
1. Need a way to provide image registry(used by deployer and finOps tools)
2. Allow the user to configure image list(option)

**Comment by linyinli** [comment]
> For image part:
> 
> 1. Need a way to provide image registry(used by deployer and finOps tools)
> 2. Allow the user to configure image list(option)

And should support image registry authentication configuration.

**Comment by gitlawr** [comment]
1. Update image list in https://github.com/seal-io/walrus/blob/main/hack/mirror/mirror_image_list.txt
2. Make the ImageRegistry setting work for workflow/deployer image.
3. Release offline deployer image

**Comment by gitlawr** [comment]
Verified in v0.4.0-rc3
