### ISSUE TITLE
View details still show username and password entered previously

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#419]
Not a big issue, but may be strange to users.
Version: v0.1.0
Step to reproduce:
1. Set build-container-image module. 
2. Set git source authentication to true and input username and password. Save change
3. Edit it again. Set authentication to false without explicitly removing username and password. Save the change.
4. View details of the module. The pervious username and password are showed.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/16434640/231652047-a2ec98dc-6461-48c3-8b9e-c5939f9b547e.png">

Should we remove the previous saved username and password when user set authentication to false and save?

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: v0.5.1

**Test Result:**
If authentication is disable, the username and password will be cleared.

<img width="2121" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/8443ec15-f1f7-4f41-87cd-e82c828d8a73">
