### ISSUE TITLE
Module version used for deploying is inconsistent with that of the system module causing instance to fail

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#434]
**Version:** main	
**UI:** dev-5f3a015
**Commit ID:** 8a1567bc58e4d079841c8721bd86308693d72b84
**Env:** Ubuntu 22.04 amd64
**Test Result:**

**Test Steps:**
1. New a template `github.com/Finenyaco/modules_test//mytest` name `mytest`
2. Create an app `myapp` and add a `mytest` module
3. Change variable `deployment_name` to `name` on GitHub
4. Deploy an instance in `myapp`

**Test Results:**
1. Fail to deploy. The latest modules are used when deploying, but the module on the system is still the previous version. 
Deployments with previous versions are expected unless the user has manually updated the template.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/26084756/231948896-e9cff794-60d5-4ec8-a438-5ab4eb3e2fe2.png">

**Comment by thxCode** [comment]
@alexcodelf any comments here? if the main branch works as expected/designed, please note here and close this issue.

**Comment by alexcodelf** [comment]
Work as expected, users need to sync template manually when their main or other branch changed.
