### ISSUE TITLE
Support textarea input for app module attributes

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#440]
There are cases when we need multiline text inputs. For example in the built-in mysql module:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/5697937/232004035-31e97245-03ba-4e89-bd89-052081a2c155.png">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main fb8dcbba8e926e4fe7b1498ae88344c9d8cbff7a
- UI version: dev-807612f

**Test Result:** pass

<img width="2463" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d0843900-03d6-4e3f-ab8f-6e4c126327c7">
