### ISSUE TITLE
Custom connector resources status is hardcode to Ready 

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#441]
**Version:** main	
**UI:** dev-5f3a015
**Commit ID:** 0c7184e88b8da7bda29804cf15ceb2bd8824763a
**Env:** Ubuntu 22.04 amd64

**Test Steps:**
 1. New a template `github.com/seal-demo/modules//aliyun-rds` name `aliyun-rds`.
 2. Create an app and add a `aliyun-rds`. Complete the corresponding configuration and save.
 3. Deploy an instance and wait for the resources created.
 4. Go to aliyun console and delete the rds instance created in step 3.
 5. Wait for the resource status updates.
 6. Check the resource status on seal.

**Test Result:** 
1. The resource status always displays as `Ready`. Status detection for custom connector resources is not supported. But the hardcoding ready status may easily mislead users.
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/26084756/232002904-534e4676-7f07-4414-8813-b7d7bf263b59.png">

**Comment by gitlawr** [comment]
Validted in main
