### ISSUE TITLE
Fail to create an instance due to incorrect data type, readNumberAsString: invalid number

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#532]
**Version:** main	
**UI:** dev-cb19061
**Commit ID:** bdcf39bbe0a7f212689b5e367a79b9c2c7cc5ccc
**Env:** MacOS 13.1, Apple M2

**Test Steps:**
1. Add a module `github.com/Finenyaco/modules_test//repo` called `repo`.

The variable spec for `test_mix` is as follow:
```
# @options [20, 30, 50, "60"]
variable "test_mix" {
  description = "Testing mixed type options"
  default     = 20
}
```
2. Create an app and add `repo` module. Select version 0.0.3, and select `60` in the drop-down list of the `test_mix` field. Save.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/26084756/234779130-1db54e28-e853-4360-bc7f-7f3d649eef65.png">

3. Create an instance.

**Test Result:** 

1. Failed to create.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/26084756/234779841-661583bf-64ff-4258-b4c5-f9848823d254.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/26084756/234780598-a16c1198-cbc5-499f-b41a-b805f30d7aef.png">

2. View seal container logs.
```
2023-04-27T06:26:52.938Z	E	apis	error requesting /v1/application-instances: readNumberAsString: invalid number, error found in #0 byte of ...|"60"|..., bigger context ...|"60"|...
github.com/seal-io/seal/pkg/apis/runtime.Erroring.func1
	github.com/seal-io/seal/pkg/apis/runtime/middleware_error.go:37
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/seal-io/seal/pkg/apis/runtime.Recovering.func1
	github.com/seal-io/seal/pkg/apis/runtime/middleware_recovery.go:36
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/seal-io/seal/pkg/apis/runtime.Logging.func2
	github.com/seal-io/seal/pkg/apis/runtime/middleware_route.go:73
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	net/http/server.go:2947
net/http.initALPNRequest.ServeHTTP
	net/http/server.go:3556
net/http.(*http2serverConn).runHandler
	net/http/h2_bundle.go:5910
```

**Comment by gitlawr** [comment]
No more valid in the latest version
