### ISSUE TITLE
Application module's sensitive field should not return value in the api result.

### ISSUE THREAD

**Issue by hibig** [seal-io/walrus#545]
Test Steps:
1.  Add a aws-rds module, db_password(sensitive is true in the schema)  field input a value
2.  save the application info
3.  refresh the page, view the aws module
4. db_password field show the value.

Expected:

db_password field  value is empty.

<img width="659" alt="截屏2023-04-28 09 40 16" src="https://user-images.githubusercontent.com/24664190/235066753-323af6f3-db0a-4013-8dda-569b13bd98f2.png">
<img width="910" alt="截屏2023-04-28 13 59 33" src="https://user-images.githubusercontent.com/24664190/235066775-b992d407-b20a-4d09-9364-71501d15c46e.png">
<img width="990" alt="截屏2023-04-28 14 00 17" src="https://user-images.githubusercontent.com/24664190/235066778-ef9d07cc-f1b4-4c69-a055-3c18d20b01d0.png">

**Comment by thxCode** [comment]
> For sensitive attributes, guide users to select an exising secret or create a new one.

Closed in favor of the above comment.
