### ISSUE TITLE
No access URL generated for mysql host

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#567]
**Version:** main	
**UI:** dev-e632ec6
**Commit ID:** dbf312b122cd051d8f7f34ca32df1cfea7e0475e
**Env:** Ubuntu 22.04 amd64

**Test Steps:**

1. Deploy a mysql db using mysql module.
2. View access URLs of the instance.

**Test Result:** 

1. No access URL generated for mysql host.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/26084756/236368805-b7d42aec-bfc3-4269-9527-66cde5ff5a1f.png">

**Comment by thxCode** [comment]
Closed in favor of https://github.com/seal-io/walrus/pull/1861, a walrus resource's `endpoints` or `walrus_endpoints` outputs determine the endpoints.
