### ISSUE TITLE
UE for secret creation 

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#622]
Version: v0.1.2-rc1
Step to reproduce:
1. Login to seal and go to Application Management - Secret.
2. Leave the project as empty and create a new secret.
3. A new global secret will be created and user may be confused although technically the behavior is correct. 
Should we consider a better management structure for secrets and variables?

![image](https://user-images.githubusercontent.com/16434640/237014305-f8eceb32-3f13-40b9-a8ec-46cb6de1be89.png)

**Comment by thxCode** [comment]
Closed as there is no concept of Secret in the latest Walrus.
