### ISSUE TITLE
Modules get stuck in initializing state if edited while refreshing

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#676]
**Version:** main	
**UI:** dev-20f1409
**Commit ID:** 3d17d748205ee5be6f34d3af5a3f6c7512d19324
**Env:** MacOS 13.1, Apple M2

**Test Steps:**

1. Go to module page.
2. Click `Edit` immediately after clicking `Refresh`. Modify the description and save.
3. View the module status on module list page.

**Test Result:** 

1. It stuck in `Initializing` state.

<img width="1114" alt="image" src="https://github.com/seal-io/seal/assets/26084756/5cc35fcb-6dc0-424a-8e3c-f2dabbb4817e">

2. Click `Refresh` again and it returned to normal.
<img width="1154" alt="image" src="https://github.com/seal-io/seal/assets/26084756/7a6c4832-41cd-4b23-90f3-f721b4d3a3e3">

**Comment by gitlawr** [comment]
No more valid in the latest version
