### ISSUE TITLE
Optimize permissions for ordinary users to view cost analysis data

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#721]
**Version:** main	
**UI:** dev-4750b53
**Commit ID:** caefc39e2dde0381a705b83d4c0d0adc2c25bf5f
**Env:** MacOS 13.1, Apple M2

**Test Steps:**

An ordinary user with access to only a few projects. But it can see the cost data of all projects which is a bit weird.

Perhaps we can disable access to view cost analysis for ordinary users. And open access to them in a future feature through a custom role policy.

<img width="1251" alt="image" src="https://github.com/seal-io/seal/assets/26084756/0843f40a-7bb9-4e84-83a7-13a94290aadf">
<img width="1248" alt="image" src="https://github.com/seal-io/seal/assets/26084756/59f989ec-67ce-4ed1-ab1f-81cd5273fe9a">

**Comment by aiwantaozi** [comment]
No more valid in the latest version
