### ISSUE TITLE
Instance stuck in deploying state

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#740]
**Version:** main	
**UI:** dev-d4bedf4
**Commit ID:** 8f7ced5963979c432a3953e24c49434c916b5853
**Env:** Ubuntu 22.04 amd64, aws EC2

**Test Steps:**
1. Deploy some instances. 

<img width="1071" alt="image" src="https://github.com/seal-io/seal/assets/26084756/3f962dd2-4a73-46d9-bf81-06b629c623d8">

**Test Result:**
1. One instance stuck in `Deploying` state. But its resources are ready. There is no way to reproduce it yet.
<img width="1081" alt="image" src="https://github.com/seal-io/seal/assets/26084756/45195218-9b25-4d9a-879d-38ef943f891f">

**Comment by thxCode** [comment]
closed in favor of #814, let's trace the inconsistent status under #840.
