### ISSUE TITLE
Optimize the error message when updating user password with less than 6 characters

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#744]
**Version:** main	
**UI:** dev-6168160
**Commit ID:** 8f7ced5963979c432a3953e24c49434c916b5853
**Env:** Ubuntu 22.04 amd64, aws EC2

**Test Steps:**

1. Create a user.
2. Change user password (less than 6 characters).

**Test Result:** 

1. Return an error `failed to update subject`, which is confusing.
<img width="934" alt="image" src="https://github.com/seal-io/seal/assets/26084756/eed2967a-7551-4334-b83b-66fd8724ca9f">

2. View logs. It said that new password must have at least 6 characters.
```
2023-06-06T08:18:19.715Z	E	api	error requesting /v1/subjects/462709585971511314: failed to update user password to casdoor: failed to set password: New password must have at least 6 characters
github.com/seal-io/seal/pkg/apis/runtime.Erroring.func1
	github.com/seal-io/seal/pkg/apis/runtime/middleware_error.go:40
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/seal-io/seal/pkg/apis/runtime.Recovering.func1
	github.com/seal-io/seal/pkg/apis/runtime/middleware_recovery.go:44
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/seal-io/seal/pkg/apis/runtime.Logging.func2
	github.com/seal-io/seal/pkg/apis/runtime/middleware_route.go:80
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2947
net/http.(*conn).serve
	net/http/server.go:1991
2023-06-06T08:18:19.715Z	D	api	500 | HTTP/1.1 |       88 B |   70.088291ms |      172.18.0.1 | PUT     /v1/subjects/462709585971511314
```

**Comment by gitlawr** [comment]
Now it says
<img width="655" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/a77ede56-5132-4b1f-9f40-eae5b6734c49">
400 bad request is unnecessary.

And add UI validation to improve UX

**Comment by hibig** [comment]
UI has been updated. @rainfd

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5cf1d9ef1dcb6bd27a686a24454d760fdc19ec22
- UI version: dev-2c89dfb

**Test Result:** pass

<img width="707" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/09717425-6913-42c3-941b-4d1d6fe9cc11">
