### ISSUE TITLE
[CLI] Enrich the output of serviceresource list

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#848]
**Version:** main	
**UI:** dev-7ca6293
**Commit ID:** 7deb37cd679efbd4397958b817a64b9a7a98b7e7
**Env:** Ubuntu 22.04 amd64, aws EC2

1. Currently the output of the serviceresource list only shows the parent resource, no resource type and sub resources. In particular, when using `webservice` template to create a service, the names of the `kubernetes_service` and `kubernetes_deployment` resources are the same, which can be confusing.

2. It must be output in yaml or json format to see the status of the resource.
```
root@ip-192-168-1-200:~# seal serviceresource list --service-id 466827061160312834
                 id                                 name                    createTime
-------------------- ------------------------------------ -----------------------------
 466827072669679618   test-testcli-test-clone/test-clone   2023-06-26T11:50:18.387465Z
 466827072669614082   test-testcli-test-clone/test-clone   2023-06-26T11:50:18.387464Z

```

<img width="1096" alt="image" src="https://github.com/seal-io/seal/assets/26084756/5c8e29ec-2942-45d4-bf5a-9244de89d123">

```
root@ip-192-168-1-200:~# seal serviceresource list --service-name mysql
                 id                       name                    createTime
-------------------- -------------------------- -----------------------------
 466828425953411074   test-testcli-mysql/mysql   2023-06-26T12:03:45.003396Z
```
<img width="1120" alt="image" src="https://github.com/seal-io/seal/assets/26084756/dfb44afc-90d1-4b46-b314-55b790723971">

**Comment by gitlawr** [comment]
No more valid in the latest version
