### ISSUE TITLE
Cannot redeploy when the service is in DeleteFailed state

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#934]
**Version:** main	
**UI:** dev-737d4f8
**Commit ID:** 7cb6b67871c99f7ad2db15fe5db5d2af65a1a6fd
**Env:** AWS EC2 Ubuntu 22.04 amd64

**Test Steps:**
1. Create a `webservice` service.
2. Shut down the Kubernetes cluster.
3. Delete the service create in step 1. 
4. Wait for the deletion to fail, and then click Deploy.
<img width="981" alt="image" src="https://github.com/seal-io/seal/assets/26084756/34e7ff6f-acb2-43e3-b5cb-a22b461a7e98">

**Test Result:** 

1. Cannot get the template information. Unable to deploy.
<img width="1391" alt="image" src="https://github.com/seal-io/seal/assets/26084756/03485ce8-f3a4-4c09-8027-c5fffee2d153">

**Comment by gitlawr** [comment]
No more valid in the latest version
