### ISSUE TITLE
[Feature Request] Show service number in environment list view

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#964]
Version: v0.2
Description: Currently we only show env name, description, create time in env list view, which is not very helpful. User may want to know how many services have been deployed in each environment and the status of them. It will be helpful If we can show this overview information in the env list view. Currently users can only click and enter each env to check.
![image](https://github.com/seal-io/seal/assets/16434640/0b4cafe8-6c4e-4034-8c01-1723a4051cc1)

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: 26ec3d124e49c0d0834e48b4e1e974d689c6a0e9
- UI version: dev-e291910

**Test Result:** 

<img width="2487" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/51b41c7b-ec6c-462c-aab2-28a3c334a4ee">

But the statistics cannot be automatically updated https://github.com/seal-io/walrus/issues/1454
