### ISSUE TITLE
Provide more methods to filter services

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#981]
**Version:** main	
**UI:** method
**Commit ID:** 68e121d64cab4d59254b9f8b69d3c5e4aafe4321
**Env:** AWS EC2 Ubuntu 22.04 amd64

Currently, we can only filter services by service name. If it can be filtered by `service status` , `templates`  or `create time`  (like last 7 days ...), I think it would be a better user experience.

<img width="1503" alt="image" src="https://github.com/seal-io/seal/assets/26084756/641761c3-3084-4393-92a5-abeb2d69320d">

**Comment by gitlawr** [comment]
No more valid in the latest version
