### ISSUE TITLE
Use seal domain for built-in template/catalog

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#990]

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main b0c3bd4666d7e891f3713760d3223998d4388a0f
- UI version: dev-c12f198

**Test Result:** pass

<img width="532" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c47861a6-5165-4dd1-a6ad-5f71dc706cd2">
<img width="2493" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5b40ae95-a63b-4803-96dd-489446eb8236">
